Repository DEFRA/waste-carriers-engine, pull requests merged in 2018-11, with the labels that each got.

#290 Add a grace window for expired regs to renew
  app/models/concerns/waste_carriers_engine/can_change_registration_status.rb
  config/application.rb
  spec/dummy/.env.example
  spec/dummy/config/application.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/requests/waste_carriers_engine/renewal_start_forms_spec.rb
  spec/support/shared_examples/request_post_form.rb
  spec/support/shared_examples/request_post_no_params_form.rb
Labels: enhancement

#296 Fix conviction check to handle grace window
  app/models/concerns/waste_carriers_engine/can_change_registration_status.rb
  app/models/waste_carriers_engine/transient_registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/requests/waste_carriers_engine/renewal_start_forms_spec.rb
  spec/support/shared_examples/request_post_form.rb
  spec/support/shared_examples/request_post_no_params_form.rb
Labels: bug

#300 Allow expired renewal to complete post declaration
  app/models/concerns/waste_carriers_engine/can_change_registration_status.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/services/waste_carriers_engine/expiry_check_service.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/services/waste_carriers_engine/expiry_check_service_spec.rb
Labels: enhancement

#302 Improve dashboard search performance
  app/models/waste_carriers_engine/transient_registration.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/support/shared_examples/transient_registration_scope.rb
Labels: enhancement

#304 Add scopes for different conviction check states
  app/models/waste_carriers_engine/transient_registration.rb
  spec/support/shared_examples/transient_registration_scope.rb
Labels: enhancement

#306 Resolve warning msg about overwiting field _id
  app/models/waste_carriers_engine/counter.rb
Labels: bug

#309 Update VCR cassettes
  spec/cassettes/company_no_inactive.yml
  spec/cassettes/company_no_not_found.yml
  spec/cassettes/company_no_valid.yml
  spec/cassettes/entity_matching_business_has_matches.yml
  spec/cassettes/entity_matching_business_no_matches.yml
  spec/cassettes/entity_matching_person_has_matches.yml
  spec/cassettes/entity_matching_person_no_matches.yml
  spec/cassettes/entity_matching_person_unicode.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#310 Block renewal rejection in initial conviction check state
  app/models/concerns/waste_carriers_engine/can_change_conviction_workflow_status.rb
  spec/models/waste_carriers_engine/conviction_sign_off_spec.rb
  spec/support/shared_examples/transient_registration_scope.rb
Labels: bug

#318 Upgrade to Rails 4.2.11
  Gemfile.lock
  waste_carriers_engine.gemspec
Labels: dependencies, security
