Repository DEFRA/waste-carriers-engine, pull requests merged in 2019-10, with the labels that each got.

#485 Update VCR cassettes
  spec/cassettes/entity_matching_business_has_matches.yml
  spec/cassettes/entity_matching_business_no_matches.yml
  spec/cassettes/entity_matching_person_has_matches.yml
  spec/cassettes/entity_matching_person_no_matches.yml
  spec/cassettes/entity_matching_person_unicode.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#486 Forms refactoring: Submit with assign and validation
  app/forms/waste_carriers_engine/bank_transfer_form.rb
  app/forms/waste_carriers_engine/base_form.rb
  app/forms/waste_carriers_engine/location_form.rb
  spec/forms/waste_carriers_engine/bank_transfer_forms_spec.rb
  spec/forms/waste_carriers_engine/base_forms_spec.rb
  spec/forms/waste_carriers_engine/cards_forms_spec.rb
  spec/forms/waste_carriers_engine/check_your_answers_forms_spec.rb
  spec/forms/waste_carriers_engine/payment_summary_forms_spec.rb
  spec/forms/waste_carriers_engine/register_in_northern_ireland_forms_spec.rb
  spec/forms/waste_carriers_engine/register_in_scotland_forms_spec.rb
  spec/forms/waste_carriers_engine/register_in_wales_forms_spec.rb
  spec/forms/waste_carriers_engine/renewal_information_forms_spec.rb
  spec/forms/waste_carriers_engine/renewal_start_forms_spec.rb
Labels: enhancement

#490 Forms refactoring - Use strong parameters in Business type form
  app/controllers/waste_carriers_engine/business_type_forms_controller.rb
  app/controllers/waste_carriers_engine/forms_controller.rb
  app/forms/waste_carriers_engine/business_type_form.rb
Labels: housekeeping

#495 Forms refactoring - Add callbacks ability to base form
  app/forms/waste_carriers_engine/base_form.rb
Labels: housekeeping

#487 Forms refactoring - Tidy up
  app/forms/waste_carriers_engine/address_form.rb
  app/forms/waste_carriers_engine/bank_transfer_form.rb
  app/forms/waste_carriers_engine/base_form.rb
  app/forms/waste_carriers_engine/cannot_renew_company_no_change_form.rb
  app/forms/waste_carriers_engine/cannot_renew_lower_tier_form.rb
  app/forms/waste_carriers_engine/cannot_renew_type_change_form.rb
  app/forms/waste_carriers_engine/cards_form.rb
  app/forms/waste_carriers_engine/cbd_type_form.rb
  app/forms/waste_carriers_engine/check_your_answers_form.rb
  app/forms/waste_carriers_engine/company_address_form.rb
  app/forms/waste_carriers_engine/company_address_manual_form.rb
  app/forms/waste_carriers_engine/company_name_form.rb
  app/forms/waste_carriers_engine/company_postcode_form.rb
  app/forms/waste_carriers_engine/construction_demolition_form.rb
  app/forms/waste_carriers_engine/contact_address_form.rb
  app/forms/waste_carriers_engine/contact_address_manual_form.rb
  app/forms/waste_carriers_engine/contact_email_form.rb
  app/forms/waste_carriers_engine/contact_name_form.rb
  app/forms/waste_carriers_engine/contact_phone_form.rb
  app/forms/waste_carriers_engine/contact_postcode_form.rb
  app/forms/waste_carriers_engine/conviction_details_form.rb
  app/forms/waste_carriers_engine/declaration_form.rb
  app/forms/waste_carriers_engine/declare_convictions_form.rb
  app/forms/waste_carriers_engine/location_form.rb
  app/forms/waste_carriers_engine/main_people_form.rb
  app/forms/waste_carriers_engine/manual_address_form.rb
  app/forms/waste_carriers_engine/other_businesses_form.rb
  app/forms/waste_carriers_engine/payment_summary_form.rb
  app/forms/waste_carriers_engine/person_form.rb
  app/forms/waste_carriers_engine/register_in_northern_ireland_form.rb
  app/forms/waste_carriers_engine/register_in_scotland_form.rb
  app/forms/waste_carriers_engine/register_in_wales_form.rb
  app/forms/waste_carriers_engine/registration_number_form.rb
  app/forms/waste_carriers_engine/renewal_complete_form.rb
  app/forms/waste_carriers_engine/renewal_information_form.rb
  app/forms/waste_carriers_engine/renewal_received_form.rb
  app/forms/waste_carriers_engine/renewal_start_form.rb
  app/forms/waste_carriers_engine/service_provided_form.rb
  app/forms/waste_carriers_engine/tier_check_form.rb
  app/forms/waste_carriers_engine/waste_types_form.rb
  app/forms/waste_carriers_engine/worldpay_form.rb
Labels: housekeeping

#494 Forms Refactoring - CBD type form
  app/controllers/waste_carriers_engine/cbd_type_forms_controller.rb
  app/forms/waste_carriers_engine/cbd_type_form.rb
  spec/support/shared_examples/validate_registration_type.rb
Labels: housekeeping

#496 Forms refactoring - Company name form
  app/controllers/waste_carriers_engine/company_name_forms_controller.rb
  app/forms/waste_carriers_engine/company_name_form.rb
  spec/support/shared_examples/validate_company_name.rb
Labels: housekeeping

#498 Forms refactoring - Construction demolition form
  app/controllers/waste_carriers_engine/construction_demolition_forms_controller.rb
  app/forms/waste_carriers_engine/construction_demolition_form.rb
  spec/factories/forms/construction_demolition_form.rb
  spec/support/shared_examples/validate_yes_no.rb
Labels: housekeeping

#497 Forms refactoring - Company postcode form
  app/controllers/waste_carriers_engine/company_postcode_forms_controller.rb
  app/forms/waste_carriers_engine/company_postcode_form.rb
  spec/factories/forms/company_postcode_form.rb
  spec/support/shared_examples/validate_postcode.rb
Labels: housekeeping

#493 Forms refactoring - Cards form
  app/controllers/waste_carriers_engine/cards_forms_controller.rb
  app/forms/waste_carriers_engine/cards_form.rb
  spec/factories/forms/cards_form.rb
  spec/forms/waste_carriers_engine/cards_forms_spec.rb
  spec/requests/waste_carriers_engine/cards_forms_spec.rb
Labels: housekeeping

#488 Forms refactoring - Remove extra reg_identifier param on submit
  app/forms/waste_carriers_engine/address_form.rb
  app/forms/waste_carriers_engine/bank_transfer_form.rb
  app/forms/waste_carriers_engine/base_form.rb
  app/forms/waste_carriers_engine/check_your_answers_form.rb
  app/forms/waste_carriers_engine/contact_email_form.rb
  app/forms/waste_carriers_engine/contact_name_form.rb
  app/forms/waste_carriers_engine/contact_phone_form.rb
  app/forms/waste_carriers_engine/contact_postcode_form.rb
  app/forms/waste_carriers_engine/declaration_form.rb
  app/forms/waste_carriers_engine/declare_convictions_form.rb
  app/forms/waste_carriers_engine/manual_address_form.rb
  app/forms/waste_carriers_engine/other_businesses_form.rb
  app/forms/waste_carriers_engine/payment_summary_form.rb
  app/forms/waste_carriers_engine/person_form.rb
  app/forms/waste_carriers_engine/register_in_northern_ireland_form.rb
  app/forms/waste_carriers_engine/register_in_scotland_form.rb
  app/forms/waste_carriers_engine/register_in_wales_form.rb
  app/forms/waste_carriers_engine/registration_number_form.rb
  app/forms/waste_carriers_engine/renewal_information_form.rb
  app/forms/waste_carriers_engine/renewal_start_form.rb
  app/forms/waste_carriers_engine/service_provided_form.rb
  app/forms/waste_carriers_engine/tier_check_form.rb
  app/forms/waste_carriers_engine/waste_types_form.rb
Labels: housekeeping

#499 Forms refactoring - Contact email form
  app/controllers/waste_carriers_engine/contact_email_forms_controller.rb
  app/forms/waste_carriers_engine/contact_email_form.rb
  spec/factories/forms/contact_email_form.rb
  spec/forms/waste_carriers_engine/contact_email_forms_spec.rb
Labels: housekeeping

#500 Forms refactoring - Contact name form
  app/controllers/waste_carriers_engine/contact_name_forms_controller.rb
  app/forms/waste_carriers_engine/contact_name_form.rb
  spec/factories/forms/contact_name_form.rb
  spec/support/shared_examples/validate_person_name.rb
Labels: housekeeping

#501 Forms refactoring - Contact Phone Number
  app/controllers/waste_carriers_engine/contact_phone_forms_controller.rb
  app/forms/waste_carriers_engine/contact_phone_form.rb
  spec/factories/forms/contact_phone_form.rb
Labels: housekeeping

#503 Forms refactoring - Declaration form
  app/controllers/waste_carriers_engine/declaration_forms_controller.rb
  app/forms/waste_carriers_engine/declaration_form.rb
  spec/factories/forms/declaration_form.rb
  spec/forms/waste_carriers_engine/declaration_forms_spec.rb
Labels: housekeeping

#504 Forms Refactoring - Declare convictions form
  app/controllers/waste_carriers_engine/declare_convictions_forms_controller.rb
  app/forms/waste_carriers_engine/declare_convictions_form.rb
  spec/factories/forms/declare_convictions_form.rb
Labels: housekeeping

#506 Forms refactoring - Other businesses
  app/controllers/waste_carriers_engine/other_businesses_forms_controller.rb
  app/forms/waste_carriers_engine/other_businesses_form.rb
  spec/factories/forms/other_businesses_form.rb
Labels: housekeeping

#505 Forms refactoring - Location form
  app/controllers/waste_carriers_engine/location_forms_controller.rb
  app/forms/waste_carriers_engine/location_form.rb
  spec/factories/forms/location_form.rb
Labels: housekeeping

#507 Forms refactoring - Registration Number form
  app/controllers/waste_carriers_engine/registration_number_forms_controller.rb
  app/forms/waste_carriers_engine/registration_number_form.rb
Labels: housekeeping

#508 Forms Refactoring - Service Provider form
  app/controllers/waste_carriers_engine/service_provided_forms_controller.rb
  app/forms/waste_carriers_engine/service_provided_form.rb
  spec/factories/forms/service_provided_form.rb
Labels: housekeeping

#509 Forms refactoring - Tier Check
  app/controllers/waste_carriers_engine/tier_check_forms_controller.rb
  app/forms/waste_carriers_engine/tier_check_form.rb
  spec/factories/forms/tier_check_form.rb
Labels: housekeeping

#511 Add search scope to Registration
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/waste_carriers_engine/transient_registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/support/shared_examples/search_scope.rb
  spec/support/shared_examples/transient_registration_scope.rb
Labels: enhancement

#510 Forms Refactoring - Check your answers form
  app/forms/waste_carriers_engine/check_your_answers_form.rb
  app/models/concerns/waste_carriers_engine/can_limit_number_of_main_people.rb
  app/models/concerns/waste_carriers_engine/can_limit_number_of_relevant_people.rb
  spec/forms/waste_carriers_engine/check_your_answers_forms_spec.rb
Labels: housekeeping

#513 Use Fetch instead of Require when fetching parameters
  app/controllers/waste_carriers_engine/business_type_forms_controller.rb
  app/controllers/waste_carriers_engine/cards_forms_controller.rb
  app/controllers/waste_carriers_engine/cbd_type_forms_controller.rb
  app/controllers/waste_carriers_engine/company_name_forms_controller.rb
  app/controllers/waste_carriers_engine/company_postcode_forms_controller.rb
  app/controllers/waste_carriers_engine/construction_demolition_forms_controller.rb
  app/controllers/waste_carriers_engine/contact_email_forms_controller.rb
  app/controllers/waste_carriers_engine/contact_name_forms_controller.rb
  app/controllers/waste_carriers_engine/contact_phone_forms_controller.rb
  app/controllers/waste_carriers_engine/contact_postcode_forms_controller.rb
  app/controllers/waste_carriers_engine/declaration_forms_controller.rb
  app/controllers/waste_carriers_engine/declare_convictions_forms_controller.rb
  app/controllers/waste_carriers_engine/location_forms_controller.rb
  app/controllers/waste_carriers_engine/other_businesses_forms_controller.rb
  app/controllers/waste_carriers_engine/registration_number_forms_controller.rb
  app/controllers/waste_carriers_engine/service_provided_forms_controller.rb
  spec/support/shared_examples/post_form.rb
Labels: bug

#515 Fix bug in CanReferenceSingleDocument
  app/models/concerns/waste_carriers_engine/can_reference_single_document_in_collection.rb
  spec/support/shared_examples/can_reference_single_document_in_collection.rb
Labels: bug

#516 Forms refactoring - Externalise AddressFinder stubs
  spec/forms/waste_carriers_engine/company_address_forms_spec.rb
  spec/forms/waste_carriers_engine/contact_address_forms_spec.rb
  spec/support/address_finder_service_stub_helper.rb
Labels: housekeeping

#514 Forms Refactoring - Address lookup forms
  app/controllers/waste_carriers_engine/company_address_forms_controller.rb
  app/controllers/waste_carriers_engine/contact_address_forms_controller.rb
  app/forms/waste_carriers_engine/address_form.rb
  app/forms/waste_carriers_engine/address_lookup_form_base.rb
  app/forms/waste_carriers_engine/company_address_form.rb
  app/forms/waste_carriers_engine/contact_address_form.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/views/waste_carriers_engine/company_address_forms/new.html.erb
  app/views/waste_carriers_engine/contact_address_forms/new.html.erb
  app/views/waste_carriers_engine/shared/_select_address.html.erb
  spec/factories/forms/company_address_form.rb
  spec/factories/forms/contact_address_form.rb
  spec/forms/waste_carriers_engine/company_address_forms_spec.rb
  spec/forms/waste_carriers_engine/contact_address_forms_spec.rb
  spec/requests/waste_carriers_engine/company_address_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_address_forms_spec.rb
Labels: housekeeping

#520 Improve metadata status checks
  app/models/concerns/waste_carriers_engine/can_change_registration_status.rb
  app/models/concerns/waste_carriers_engine/can_check_registration_status.rb
  app/models/waste_carriers_engine/registration.rb
  app/models/waste_carriers_engine/transient_registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/support/shared_examples/can_check_registration_status.rb
Labels: enhancement

#522 Deal with special characters in search scope
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  spec/support/shared_examples/search_scope.rb
Labels: bug

#521 Add registration.can_start_renewal?
  app/models/waste_carriers_engine/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: enhancement

#518 Assign correct type to object
  app/models/concerns/waste_carriers_engine/can_reference_single_document_in_collection.rb
  spec/support/shared_examples/can_reference_single_document_in_collection.rb
Labels: enhancement

#524 Fix bug in assigning empty hash
  app/models/concerns/waste_carriers_engine/can_reference_single_document_in_collection.rb
  spec/support/shared_examples/can_reference_single_document_in_collection.rb
Labels: bug

#519 Forms refactoring: Address Manual forms
  app/controllers/waste_carriers_engine/company_address_manual_forms_controller.rb
  app/controllers/waste_carriers_engine/contact_address_manual_forms_controller.rb
  app/forms/concerns/waste_carriers_engine/can_clear_address_finder_error.rb
  app/forms/concerns/waste_carriers_engine/can_validate_manual_address.rb
  app/forms/waste_carriers_engine/company_address_manual_form.rb
  app/forms/waste_carriers_engine/contact_address_manual_form.rb
  app/forms/waste_carriers_engine/manual_address_form.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/views/waste_carriers_engine/company_address_manual_forms/new.html.erb
  app/views/waste_carriers_engine/contact_address_manual_forms/new.html.erb
  app/views/waste_carriers_engine/shared/_manual_address.html.erb
  config/locales/forms/company_address_forms/en.yml
  config/locales/forms/company_address_manual_forms/en.yml
  config/locales/forms/contact_address_forms/en.yml
  config/locales/forms/contact_address_manual_forms/en.yml
  lib/waste_carriers_engine/engine.rb
  spec/factories/address.rb
  spec/factories/forms/company_address_manual_form.rb
  spec/factories/forms/contact_address_manual_form.rb
  spec/factories/transient_registration.rb
  spec/forms/waste_carriers_engine/company_address_manual_forms_spec.rb
  spec/forms/waste_carriers_engine/contact_address_manual_forms_spec.rb
  spec/requests/waste_carriers_engine/company_address_forms_spec.rb
  spec/requests/waste_carriers_engine/company_address_manual_forms_spec.rb
  spec/requests/waste_carriers_engine/company_postcode_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_address_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_address_manual_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_postcode_forms_spec.rb
Labels: housekeeping

#525 Forms refactoring - Bank transfer
  app/controllers/waste_carriers_engine/bank_transfer_forms_controller.rb
  app/forms/waste_carriers_engine/bank_transfer_form.rb
Labels: housekeeping

#526 Forms refactoring - Create concern for Cannot submit
  app/forms/concerns/waste_carriers_engine/cannot_submit.rb
  app/forms/waste_carriers_engine/cannot_renew_company_no_change_form.rb
  app/forms/waste_carriers_engine/cannot_renew_lower_tier_form.rb
  app/forms/waste_carriers_engine/cannot_renew_type_change_form.rb
  app/forms/waste_carriers_engine/renewal_complete_form.rb
  app/forms/waste_carriers_engine/renewal_received_form.rb
Labels: housekeeping

#528 Forms refactoring - Payment summary form
  app/controllers/waste_carriers_engine/payment_summary_forms_controller.rb
  app/forms/waste_carriers_engine/payment_summary_form.rb
  spec/factories/forms/payment_summary_form.rb
  spec/forms/waste_carriers_engine/payment_summary_forms_spec.rb
Labels: housekeeping

#527 Forms refactoring - People forms controllers
  app/controllers/waste_carriers_engine/conviction_details_forms_controller.rb
  app/controllers/waste_carriers_engine/main_people_forms_controller.rb
Labels: housekeeping

#529 Forms refactoring - Waste types
  app/controllers/waste_carriers_engine/waste_types_forms_controller.rb
  app/forms/waste_carriers_engine/waste_types_form.rb
  spec/factories/forms/waste_types_form.rb
Labels: housekeeping

#530 Forms refactoring - Remove temp code in BaseForm
  app/controllers/waste_carriers_engine/forms_controller.rb
Labels: housekeeping

#531 Forms refactoring - Remove temporary hack in specs
  spec/support/shared_examples/validate_company_name.rb
Labels: housekeeping

#536 Use helpers on shared methods in rspec test suite
  spec/support/form_request_helpers.rb
  spec/support/shared_examples/post_form.rb
  spec/support/shared_examples/request_post_no_params_form.rb
Labels: housekeeping

#533 Move setting up of ASSISTED_DIGITAL flag in AASM machine
  app/models/concerns/waste_carriers_engine/can_change_workflow_status.rb
  app/models/waste_carriers_engine/transient_registration.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/requests/waste_carriers_engine/bank_transfer_forms_spec.rb
  spec/requests/waste_carriers_engine/worldpay_forms_spec.rb
  spec/services/waste_carriers_engine/renewal_completion_service_spec.rb
Labels: bug, housekeeping

#534 Add payment check methods to registration
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/waste_carriers_engine/registration.rb
  app/models/waste_carriers_engine/transient_registration.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: enhancement

#535 Add pending_manual_conviction_check? method to registration
  app/models/waste_carriers_engine/registration.rb
  spec/factories/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: enhancement

#539 Remove redundant code
  app/forms/waste_carriers_engine/base_form.rb
Labels: housekeeping

#541 Show validation errors in-line with checkbox
  app/views/waste_carriers_engine/declaration_forms/new.html.erb
Labels: housekeeping

#544 Add method to access amount paid by user
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: enhancement
