Repository DEFRA/waste-carriers-engine, pull requests merged in 2019-11, with the labels that each got.

#547 Update VCR cassettes
  spec/cassettes/entity_matching_business_has_matches.yml
  spec/cassettes/entity_matching_business_no_matches.yml
  spec/cassettes/entity_matching_person_has_matches.yml
  spec/cassettes/entity_matching_person_no_matches.yml
  spec/cassettes/entity_matching_person_unicode.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#545 Stop validating worldpay source param
  app/services/waste_carriers_engine/worldpay_validator_service.rb
  spec/services/waste_carriers_engine/worldpay_validator_service_spec.rb
Labels: enhancement

#551 Use new RenewingRegistration in factories
  spec/factories/forms/bank_transfer_form.rb
  spec/factories/forms/base_form.rb
  spec/factories/forms/business_type_form.rb
  spec/factories/forms/cannot_renew_company_no_change_form.rb
  spec/factories/forms/cannot_renew_lower_tier_form.rb
  spec/factories/forms/cannot_renew_type_change_form.rb
  spec/factories/forms/cards_form.rb
  spec/factories/forms/cbd_type_form.rb
  spec/factories/forms/check_your_answers_form.rb
  spec/factories/forms/company_address_form.rb
  spec/factories/forms/company_address_manual_form.rb
  spec/factories/forms/company_name_form.rb
  spec/factories/forms/company_postcode_form.rb
  spec/factories/forms/construction_demolition_form.rb
  spec/factories/forms/contact_address_form.rb
  spec/factories/forms/contact_address_manual_form.rb
  spec/factories/forms/contact_email_form.rb
  spec/factories/forms/contact_name_form.rb
  spec/factories/forms/contact_phone_form.rb
  spec/factories/forms/contact_postcode_form.rb
  spec/factories/forms/conviction_details_form.rb
  spec/factories/forms/declaration_form.rb
  spec/factories/forms/declare_convictions_form.rb
  spec/factories/forms/location_form.rb
  spec/factories/forms/main_people_form.rb
  spec/factories/forms/other_businesses_form.rb
  spec/factories/forms/payment_summary_form.rb
  spec/factories/forms/register_in_northern_ireland_form.rb
  spec/factories/forms/register_in_scotland_form.rb
  spec/factories/forms/register_in_wales_form.rb
  spec/factories/forms/registration_number_form.rb
  spec/factories/forms/renewal_complete_form.rb
  spec/factories/forms/renewal_information_form.rb
  spec/factories/forms/renewal_received_form.rb
  spec/factories/forms/renewal_start_form.rb
  spec/factories/forms/service_provided_form.rb
  spec/factories/forms/tier_check_form.rb
  spec/factories/forms/waste_types_form.rb
  spec/factories/forms/worldpay_form.rb
Labels: enhancement

#548 Create model for conviction entities
  app/models/waste_carriers_engine/convictions_check/entity.rb
  spec/models/waste_carriers_engine/convictions_check/entity_spec.rb
Labels: enhancement

#557 Reset codeclimate to fix CI
  .travis.yml
Labels: housekeeping

#554 Set up PersonMatchService for individual conviction checks
  app/services/waste_carriers_engine/base_service.rb
  app/services/waste_carriers_engine/convictions_check/person_match_service.rb
  spec/services/waste_carriers_engine/convictions_check/person_match_service_spec.rb
Labels: enhancement

#555 Set up OrganisationMatchService for org-level conviction checks
  app/services/waste_carriers_engine/convictions_check/base_match_service.rb
  app/services/waste_carriers_engine/convictions_check/organisation_match_service.rb
  app/services/waste_carriers_engine/convictions_check/person_match_service.rb
  spec/services/waste_carriers_engine/convictions_check/organisation_match_service_spec.rb
Labels: enhancement

#556 Update EntityMatchingService to call new convictions check
  app/controllers/waste_carriers_engine/declaration_forms_controller.rb
  app/models/waste_carriers_engine/conviction_search_result.rb
  app/services/waste_carriers_engine/conviction_data_service.rb
  app/services/waste_carriers_engine/entity_matching_service.rb
  spec/cassettes/entity_matching_business_has_matches.yml
  spec/cassettes/entity_matching_business_no_matches.yml
  spec/cassettes/entity_matching_person_has_matches.yml
  spec/cassettes/entity_matching_person_no_matches.yml
  spec/cassettes/entity_matching_person_unicode.yml
  spec/models/waste_carriers_engine/conviction_search_result_spec.rb
  spec/services/waste_carriers_engine/conviction_data_service_spec.rb
  spec/services/waste_carriers_engine/entity_matching_service_spec.rb
Labels: enhancement

#560 Remove alias to `revoked` and add specific method
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/waste_carriers_engine/transient_registration.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
Labels: enhancement, housekeeping

#561 Update VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#562 Check for matching company_no before name in convictions
  app/models/waste_carriers_engine/convictions_check/entity.rb
  spec/models/waste_carriers_engine/convictions_check/entity_spec.rb
Labels: bug

#563 Add lower and upper tier check methods to Registrations
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/waste_carriers_engine/registration.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: enhancement

#564 Conviction match on name only if no matches with DOB
  app/models/waste_carriers_engine/convictions_check/entity.rb
  spec/models/waste_carriers_engine/convictions_check/entity_spec.rb
Labels: bug

#566 Add cache and use find_by to registration method
  app/models/waste_carriers_engine/renewing_registration.rb
  spec/models/waste_carriers_engine/workflow_states/transient_registration_registration_number_form_spec.rb
Labels: enhancement

#565 Treat punctuation as optional for org name conviction checks
  app/models/waste_carriers_engine/convictions_check/entity.rb
  spec/models/waste_carriers_engine/convictions_check/entity_spec.rb
Labels: bug

#568 Fix codeclimate badges
  README.md
Labels: housekeeping
