Repository DEFRA/waste-carriers-engine, pull requests merged in 2019-12, with the labels that each got.

#571 Update VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#572 Add shared convictions scopes for regs and transient_regs
  app/models/concerns/waste_carriers_engine/can_filter_conviction_status.rb
  app/models/waste_carriers_engine/registration.rb
  app/models/waste_carriers_engine/transient_registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/support/shared_examples/can_filter_conviction_status.rb
Labels: enhancement

#574 Add scope to deal with conviction_sign_offs from frontend
  app/models/concerns/waste_carriers_engine/can_filter_conviction_status.rb
  spec/support/shared_examples/can_filter_conviction_status.rb
Labels: enhancement

#570 Add service to order copy cards
  app/models/waste_carriers_engine/order.rb
  app/services/waste_carriers_engine/order_additional_cards_service.rb
  spec/services/waste_carriers_engine/order_additional_cards_service_spec.rb
Labels: enhancement

#573 Add OrderCopyCardsRegistration model
  app/models/concerns/waste_carriers_engine/can_use_order_copy_cards_workflow.rb
  app/models/waste_carriers_engine/order_copy_cards_registration.rb
  app/models/waste_carriers_engine/transient_registration.rb
  spec/factories/order_copy_cards_registration.rb
  spec/forms/waste_carriers_engine/company_address_forms_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_bank_transfer_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_payment_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/wordpay_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
  spec/support/shared_examples/transient_registration_named_scopes.rb
Labels: enhancement

#577 Move prepare for payment method in transient object
  app/controllers/waste_carriers_engine/bank_transfer_forms_controller.rb
  app/controllers/waste_carriers_engine/worldpay_forms_controller.rb
  app/models/waste_carriers_engine/finance_details.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_carriers_engine/finance_details_spec.rb
  spec/models/waste_carriers_engine/order_item_spec.rb
  spec/models/waste_carriers_engine/order_spec.rb
  spec/models/waste_carriers_engine/payment_spec.rb
  spec/requests/waste_carriers_engine/bank_transfer_forms_spec.rb
  spec/requests/waste_carriers_engine/worldpay_forms_spec.rb
  spec/services/waste_carriers_engine/smart_answers_checker_service_spec.rb
  spec/services/waste_carriers_engine/worldpay_service_spec.rb
  spec/services/waste_carriers_engine/worldpay_validator_service_spec.rb
  spec/support/shared_examples/request_get_unsuccessful_worldpay_response.rb
  spec/support/shared_examples/worldpay_service_valid_unsuccessful_action.rb
Labels: enhancement

#576 Add copy cards main forms
  app/controllers/waste_carriers_engine/base_order_copy_cards_forms_controller.rb
  app/controllers/waste_carriers_engine/copy_cards_forms_controller.rb
  app/controllers/waste_carriers_engine/copy_cards_payment_forms_controller.rb
  app/forms/waste_carriers_engine/copy_cards_form.rb
  app/forms/waste_carriers_engine/copy_cards_payment_form.rb
  app/views/waste_carriers_engine/copy_cards_forms/new.html.erb
  app/views/waste_carriers_engine/copy_cards_payment_forms/new.html.erb
  config/routes.rb
  spec/dummy/app/models/ability.rb
  spec/requests/waste_carriers_engine/copy_cards_forms_spec.rb
  spec/requests/waste_carriers_engine/copy_cards_payment_forms_spec.rb
Labels: enhancement

#580 Add service that generates Base(58) secure tokens
  app/services/waste_carriers_engine/secure_token_service.rb
  spec/services/waste_carriers_engine/secure_token_service_spec.rb
Labels: enhancement

#581 Refuse or revoke registration after failed conviction check
  app/models/concerns/waste_carriers_engine/can_change_conviction_workflow_status.rb
  spec/models/waste_carriers_engine/conviction_sign_off_spec.rb
  spec/support/shared_examples/transient_registration_named_scopes.rb
Labels: enhancement

#582 Remove order copy cards shared form and create concern
  app/controllers/concerns/waste_carriers_engine/order_copy_cards_permission_checks.rb
  app/controllers/waste_carriers_engine/copy_cards_forms_controller.rb
  app/controllers/waste_carriers_engine/copy_cards_payment_forms_controller.rb
  app/controllers/waste_carriers_engine/forms_controller.rb
  config/locales/models/order_copy_cards_registrations/en.yml
  spec/factories/order_copy_cards_registration.rb
  spec/requests/waste_carriers_engine/copy_cards_payment_forms_spec.rb
Labels: enhancement

#583 Set up RegistrationCompletionService
  app/services/waste_carriers_engine/registration_completion_service.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
Labels: enhancement

#584 Persist setting of expiries_on when activating
  app/models/concerns/waste_carriers_engine/can_change_registration_status.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: bug

#587 Externalise permission checks logic into services
  app/controllers/concerns/waste_carriers_engine/order_copy_cards_permission_checks.rb
  app/controllers/waste_carriers_engine/copy_cards_forms_controller.rb
  app/controllers/waste_carriers_engine/copy_cards_payment_forms_controller.rb
  app/controllers/waste_carriers_engine/forms_controller.rb
  app/models/waste_carriers_engine/permission_checks_result.rb
  app/services/waste_carriers_engine/base_registration_permission_checks_service.rb
  app/services/waste_carriers_engine/flow_permission_checks_service.rb
  app/services/waste_carriers_engine/order_copy_cards_registration_permission_checks_service.rb
  app/services/waste_carriers_engine/renewing_registration_permission_checks_service.rb
  spec/models/waste_carriers_engine/permission_checks_result_spec.rb
  spec/services/waste_carriers_engine/flow_permission_checks_service_spec.rb
  spec/services/waste_carriers_engine/order_copy_cards_registration_permission_checks_service_spec.rb
  spec/services/waste_carriers_engine/renewing_registration_permission_checks_service_spec.rb
Labels: enhancement, housekeeping

#585 Send confirmation email when registration is completed
  app/mailers/waste_carriers_engine/base_mailer.rb
  app/mailers/waste_carriers_engine/new_registration_mailer.rb
  app/mailers/waste_carriers_engine/renewal_mailer.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.html.erb
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.txt.erb
  config/locales/mailers/new_registration_mailer.en.yml
  spec/mailers/waste_carriers_engine/new_registration_mailer_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
Labels: enhancement

#588 Change complete workflow to specific copy cards complete status
  app/models/concerns/waste_carriers_engine/can_use_order_copy_cards_workflow.rb
  config/routes.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_bank_transfer_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/wordpay_form_spec.rb
Labels: enhancement

#589 Copy cards bank transfer form
  app/controllers/waste_carriers_engine/copy_cards_bank_transfer_forms_controller.rb
  app/forms/waste_carriers_engine/copy_cards_bank_transfer_form.rb
  app/models/waste_carriers_engine/order_copy_cards_registration.rb
  app/services/waste_carriers_engine/order_additional_cards_service.rb
  app/views/waste_carriers_engine/copy_cards_bank_transfer_forms/new.html.erb
  spec/factories/finance_details.rb
  spec/factories/forms/copy_cards_bank_transfer_form.rb
  spec/factories/order.rb
  spec/factories/order_copy_cards_registration.rb
  spec/forms/waste_carriers_engine/copy_cards_bank_transfer_form_spec.rb
  spec/requests/waste_carriers_engine/copy_cards_bank_transfer_forms_spec.rb
  spec/services/waste_carriers_engine/order_additional_cards_service_spec.rb
Labels: enhancement

#592 Order Copy Cards form view
  app/models/waste_carriers_engine/order_copy_cards_registration.rb
  app/views/waste_carriers_engine/copy_cards_forms/new.html.erb
  config/locales/forms/copy_cards_forms/en.yml
Labels: enhancement

#590 Order copy cards completion service
  app/services/concerns/waste_carriers_engine/can_merge_finance_details.rb
  app/services/waste_carriers_engine/order_copy_cards_completion_service.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  lib/waste_carriers_engine/engine.rb
  spec/services/waste_carriers_engine/order_copy_cards_completion_service_spec.rb
Labels: enhancement

#594 Implement view for bank transfer page on order copy cards flow
  app/views/waste_carriers_engine/copy_cards_bank_transfer_forms/new.html.erb
  config/locales/forms/copy_cards_bank_transfer_forms/en.yml
Labels: enhancement

#595 Implement controller and form for the copy cards order completed form
  app/controllers/waste_carriers_engine/copy_cards_order_completed_forms_controller.rb
  app/forms/waste_carriers_engine/copy_cards_order_completed_form.rb
  app/views/waste_carriers_engine/copy_cards_order_completed_forms/new.html.erb
  spec/requests/waste_carriers_engine/copy_cards_order_completed_forms_spec.rb
Labels: enhancement

#593 Implement view for Order copy cards payment form
  app/views/waste_carriers_engine/copy_cards_payment_forms/new.html.erb
  config/locales/forms/copy_cards_payment_forms/en.yml
  spec/factories/order_copy_cards_registration.rb
  spec/requests/waste_carriers_engine/copy_cards_payment_forms_spec.rb
Labels: enhancement

#597 Update BaseForm to work with Registrations
  app/forms/waste_carriers_engine/base_form.rb
  spec/forms/waste_carriers_engine/base_forms_spec.rb
Labels: bug

#602 Implement order completed form view
  app/models/waste_carriers_engine/order_copy_cards_registration.rb
  app/views/shared/_message.html.erb
  app/views/shared/_success.html.erb
  app/views/waste_carriers_engine/copy_cards_order_completed_forms/new.html.erb
  config/locales/forms/copy_cards_order_completed_forms/en.yml
  spec/dummy/config/routes.rb
Labels: enhancement

#601 Delegate registered address to transient object
  app/models/waste_carriers_engine/order_copy_cards_registration.rb
Labels: enhancement

#600 Fix back buttons on copy cards journey pages
  app/views/waste_carriers_engine/copy_cards_bank_transfer_forms/new.html.erb
  app/views/waste_carriers_engine/copy_cards_payment_forms/new.html.erb
Labels: enhancement

#599 Fix classes and html tag for objects in the page
  app/views/waste_carriers_engine/copy_cards_payment_forms/new.html.erb
  config/locales/forms/copy_cards_payment_forms/en.yml
Labels: enhancement

#598 Fx bug on renewal start journey redirect
  app/controllers/waste_carriers_engine/renewal_start_forms_controller.rb
  app/forms/waste_carriers_engine/renewal_start_form.rb
  spec/requests/waste_carriers_engine/renewal_start_forms_spec.rb
Labels: enhancement

#596 Redirects to the correct workflow state when an order is in progress
  app/controllers/waste_carriers_engine/copy_cards_forms_controller.rb
  app/forms/waste_carriers_engine/copy_cards_form.rb
  spec/factories/order_copy_cards_registration.rb
  spec/requests/waste_carriers_engine/copy_cards_forms_spec.rb
Labels: enhancement

#604 Secure token - Change more reg_identifier to token
  app/views/waste_carriers_engine/company_address_forms/new.html.erb
  app/views/waste_carriers_engine/company_address_manual_forms/new.html.erb
  app/views/waste_carriers_engine/company_postcode_forms/new.html.erb
  app/views/waste_carriers_engine/contact_address_forms/new.html.erb
  app/views/waste_carriers_engine/contact_address_manual_forms/new.html.erb
  app/views/waste_carriers_engine/contact_postcode_forms/new.html.erb
Labels: bug, enhancement

#606 Update VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#603 Add email for completed copy cards order
  app/mailers/waste_carriers_engine/order_copy_cards_mailer.rb
  app/presenters/waste_carriers_engine/order_copy_cards_mailer_presenter.rb
  app/services/waste_carriers_engine/order_copy_cards_completion_service.rb
  app/views/waste_carriers_engine/order_copy_cards_mailer/send_order_completed_email.html.erb
  config/initializers/date_formats.rb
  config/locales/mailers/order_copy_cards_mailer.yml
  spec/presenters/waste_carriers_engine/order_copy_cards_mailer_presenter_spec.rb
  spec/services/waste_carriers_engine/order_copy_cards_completion_service_spec.rb
Labels: enhancement

#610 Fix typo in error message
  config/locales/forms/copy_cards_payment_forms/en.yml
Labels: bug

#613 Add label to flash messages
  app/views/shared/_message.html.erb
  app/views/shared/_success.html.erb
Labels: bug

#612 Use correct balance when displaying bank transfer info
  app/models/waste_carriers_engine/transient_registration.rb
  app/views/waste_carriers_engine/copy_cards_bank_transfer_forms/new.html.erb
Labels: bug

#609 Change validation message to represent real maximum
  config/locales/forms/copy_cards_forms/en.yml
Labels: bug

#605 Add email for awaiting payment copy card orders
  app/mailers/waste_carriers_engine/order_copy_cards_mailer.rb
  app/services/waste_carriers_engine/order_copy_cards_completion_service.rb
  app/views/waste_carriers_engine/order_copy_cards_mailer/send_awaiting_payment_email.html.erb
  config/locales/mailers/order_copy_cards_mailer.yml
  spec/factories/order.rb
  spec/requests/waste_carriers_engine/copy_cards_order_completed_forms_spec.rb
  spec/services/waste_carriers_engine/order_copy_cards_completion_service_spec.rb
Labels: enhancement

#616 Fix errors in pluralisation and remove dots
  app/models/waste_carriers_engine/order_item.rb
  config/locales/mailers/order_copy_cards_mailer.en.yml
  spec/models/waste_carriers_engine/order_item_spec.rb
Labels: enhancement

#617 Add pluralisation for copy cards email
  app/mailers/waste_carriers_engine/order_copy_cards_mailer.rb
  app/models/waste_carriers_engine/order_item.rb
  app/presenters/waste_carriers_engine/order_copy_cards_mailer_presenter.rb
  app/views/waste_carriers_engine/order_copy_cards_mailer/send_order_completed_email.html.erb
  config/locales/mailers/order_copy_cards_mailer.en.yml
  spec/factories/registration.rb
  spec/mailers/waste_carriers_engine/order_copy_cards_mailer_spec.rb
  spec/models/waste_carriers_engine/order_item_spec.rb
  spec/presenters/waste_carriers_engine/order_copy_cards_mailer_presenter_spec.rb
Labels: bug

#618 Change payment date_entered to be a DateTime
  app/models/waste_carriers_engine/payment.rb
Labels: enhancement

#620 Add expire! method to registration model
  app/models/waste_carriers_engine/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: enhancement

#619 Add scopes for finding registrations to expire
  app/models/waste_carriers_engine/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: enhancement

#621 Return default postcode when building XML for Worldpay
  app/services/waste_carriers_engine/worldpay_xml_service.rb
Labels: bug

#622 Add workflow and model for ceased or revoked
  app/models/concerns/waste_carriers_engine/can_use_ceased_or_revoked_registration_workflow.rb
  app/models/waste_carriers_engine/ceased_or_revoked_registration.rb
  spec/factories/ceased_or_revoked_registration.rb
  spec/models/waste_carriers_engine/ceased_or_revoked_registration_spec.rb
  spec/models/waste_carriers_engine/ceased_or_revoked_registration_workflow/cease_or_revoke_form_spec.rb
  spec/models/waste_carriers_engine/ceased_or_revoked_registration_workflow/ceased_or_revoked_confirm_form_spec.rb
Labels: enhancement

#623 Ceased or revoked routes
  config/routes.rb
Labels: enhancement

#625 Update VCR Cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
  spec/requests/waste_carriers_engine/worldpay_forms_spec.rb
Labels: housekeeping

#624 Ceased or revoked - start form
  app/controllers/waste_carriers_engine/cease_or_revoke_forms_controller.rb
  app/forms/waste_carriers_engine/cease_or_revoke_form.rb
  app/forms/waste_carriers_engine/ceased_or_revoked_confirm_form.rb
  app/models/waste_carriers_engine/ceased_or_revoked_registration.rb
  app/services/waste_carriers_engine/ceased_or_revoked_registration_permission_checks_service.rb
  app/services/waste_carriers_engine/flow_permission_checks_service.rb
  app/views/waste_carriers_engine/cease_or_revoke_forms/new.html.erb
  config/locales/forms/cease_or_revoke_forms/en.yml
  config/locales/models/ceased_or_revoked_registrations/en.yml
  config/routes.rb
  spec/dummy/app/models/ability.rb
  spec/factories/ceased_or_revoked_registration.rb
  spec/requests/waste_carriers_engine/cease_or_revoke_forms_spec.rb
  spec/services/waste_carriers_engine/flow_permission_checks_service_spec.rb
Labels: enhancement

#626 Add delete path to transient registrations
  app/controllers/waste_carriers_engine/transient_registrations_controller.rb
  config/routes.rb
  spec/requests/waste_carriers_engine/transient_registrations_spec.rb
Labels: enhancement

#627 Add ceased or revoked completion service
  app/services/waste_carriers_engine/ceased_or_revoked_completion_service.rb
  spec/services/waste_carriers_engine/ceased_or_revoked_completion_service_spec.rb
Labels: enhancement

#628 Add confirm form to revoke or cease flow
  app/controllers/waste_carriers_engine/ceased_or_revoked_confirm_forms_controller.rb
  app/forms/waste_carriers_engine/ceased_or_revoked_confirm_form.rb
  app/views/waste_carriers_engine/ceased_or_revoked_confirm_forms/new.html.erb
  config/locales/forms/ceased_or_revoked_confirm_forms/en.yml
  config/routes.rb
  spec/requests/waste_carriers_engine/ceased_or_revoked_confirm_forms_spec.rb
Labels: enhancement

#629 Externalise view code for company details
  app/controllers/waste_carriers_engine/ceased_or_revoked_confirm_forms_controller.rb
  app/views/shared/_company_details_panel.html.erb
  app/views/waste_carriers_engine/cease_or_revoke_forms/new.html.erb
  app/views/waste_carriers_engine/ceased_or_revoked_confirm_forms/new.html.erb
  config/locales/forms/cease_or_revoke_forms/en.yml
  config/locales/forms/ceased_or_revoked_confirm_forms/en.yml
  config/locales/shared/company_details_panel.en.yml
Labels: enhancement
