Repository DEFRA/waste-carriers-engine, pull requests merged in 2020-07, with the labels that each got.

#872 Promote little FeatureToggle to be a proper Model
  app/models/waste_carriers_engine/feature_toggle.rb
  spec/factories/feature_toggle.rb
  spec/models/waste_carriers_engine/feature_toggle_spec.rb
Labels: enhancement

#874 Remove unnecessary links from Devise code
  app/views/devise/shared/_links.html.erb
Labels: housekeeping

#875 Fix missing 'skip to manual entry' link on postcode lookups
  app/validators/concerns/waste_carriers_engine/can_add_validation_errors.rb
  app/validators/waste_carriers_engine/address_validator.rb
  app/validators/waste_carriers_engine/company_name_validator.rb
  app/validators/waste_carriers_engine/matching_email_validator.rb
  app/validators/waste_carriers_engine/person_name_validator.rb
  app/validators/waste_carriers_engine/postcode_validator.rb
  app/validators/waste_carriers_engine/reg_identifier_validator.rb
  app/validators/waste_carriers_engine/registration_type_validator.rb
  app/validators/waste_carriers_engine/yes_no_validator.rb
Labels: bug

#878 Fix accidental duplication of paragraph names
  app/views/waste_carriers_engine/renewal_complete_forms/new.html.erb
  config/locales/forms/renewal_complete_forms/en.yml
Labels: bug

#879 Don't copy expires_on around when editing
  app/models/waste_carriers_engine/edit_registration.rb
  app/services/waste_carriers_engine/edit_completion_service.rb
  spec/models/waste_carriers_engine/edit_registration_spec.rb
  spec/requests/waste_carriers_engine/edit_complete_forms_spec.rb
  spec/services/waste_carriers_engine/edit_completion_service_spec.rb
Labels: bug

#886 Update defra-ruby-alert
  Gemfile.lock
  lib/waste_carriers_engine.rb
  spec/dummy/config/initializers/waste_carriers_engine.rb
  waste_carriers_engine.gemspec
Labels: housekeeping

#887 Remove link to certificate from renewal complete
  app/views/waste_carriers_engine/renewal_complete_forms/new.html.erb
  config/locales/forms/renewal_complete_forms/en.yml
Labels: enhancement

#881 Add receipt email to journey end screens pending convictions
  app/views/waste_carriers_engine/registration_received_pending_conviction_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_received_pending_conviction_forms/new.html.erb
  config/locales/forms/registration_completed_forms/en.yml
  config/locales/forms/registration_received_pending_conviction_forms/en.yml
  config/locales/forms/registration_received_pending_worldpay_payment_forms/en.yml
  config/locales/forms/renewal_complete_forms/en.yml
  config/locales/forms/renewal_received_pending_conviction_forms/en.yml
  config/locales/forms/renewal_received_pending_worldpay_payment_forms/en.yml
Labels: bug

#888 Add mention of payment conf. to bank transfer
  app/views/waste_carriers_engine/confirm_bank_transfer_forms/new.html.erb
  config/locales/forms/confirm_bank_transfer_forms/en.yml
Labels: enhancement

#889 Revert addition of payment receipt screen
  app/controllers/waste_carriers_engine/receipt_email_forms_controller.rb
  app/forms/waste_carriers_engine/receipt_email_form.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/models/concerns/waste_carriers_engine/can_use_renewing_registration_workflow.rb
  app/views/waste_carriers_engine/receipt_email_forms/new.html.erb
  config/locales/forms/receipt_email_forms/en.yml
  config/routes.rb
  spec/factories/forms/receipt_email_form.rb
  spec/forms/waste_carriers_engine/receipt_email_forms_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/cards_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/payment_summary_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/receipt_email_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cards_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/payment_summary_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/receipt_email_form_spec.rb
  spec/requests/waste_carriers_engine/payment_summary_forms_spec.rb
  spec/requests/waste_carriers_engine/receipt_email_forms_spec.rb
Labels: enhancement

#890 Add payment email section to payment summary page
  app/controllers/waste_carriers_engine/payment_summary_forms_controller.rb
  app/forms/waste_carriers_engine/payment_summary_form.rb
  app/views/waste_carriers_engine/payment_summary_forms/new.html.erb
  config/locales/forms/payment_summary_forms/en.yml
  spec/forms/waste_carriers_engine/payment_summary_forms_spec.rb
  spec/requests/waste_carriers_engine/payment_summary_forms_spec.rb
Labels: enhancement

#893 Refactor ExpiryCheckService for easier overriding
  app/services/waste_carriers_engine/expiry_check_service.rb
Labels: housekeeping

#892 Hide receipt email on payment summary unless WorldPay selected
  app/assets/javascripts/receipt_email.js
  app/views/waste_carriers_engine/payment_summary_forms/new.html.erb
  config/initializers/assets.rb
Labels: enhancement

#894 Add host_is_back_office flag to config
  lib/waste_carriers_engine.rb
Labels: enhancement

#895 Hide payment confirmation in back-office
  app/forms/waste_carriers_engine/payment_summary_form.rb
  app/views/waste_carriers_engine/payment_summary_forms/new.html.erb
  spec/forms/waste_carriers_engine/payment_summary_forms_spec.rb
Labels: enhancement

#896 Hide payment confirmation in bank transfer page
  app/views/waste_carriers_engine/confirm_bank_transfer_forms/new.html.erb
  config/locales/forms/confirm_bank_transfer_forms/en.yml
Labels: enhancement

#897 Hide payment confirmation in 'end' pages
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_conviction_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_worldpay_payment_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_complete_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_received_pending_conviction_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_received_pending_worldpay_payment_forms/new.html.erb
  config/locales/forms/registration_received_pending_worldpay_payment_forms/en.yml
Labels: enhancement

#891 Add payment confirmation email to Edit
  app/presenters/waste_carriers_engine/edit_form_presenter.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  config/locales/forms/edit_forms/en.yml
  spec/presenters/waste_carriers_engine/edit_form_presenter_spec.rb
Labels: enhancement

#898 Generate renewal token when one is requested
  app/models/waste_carriers_engine/registration.rb
  spec/dummy/.ruby-version
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/requests/waste_carriers_engine/renews_spec.rb
  spec/services/waste_carriers_engine/renewal_completion_service_spec.rb
Labels: enhancement

#899 Do not copy receipt_email when init. renewal
  app/models/waste_carriers_engine/renewing_registration.rb
Labels: bug

#900 Remove magic link constraint for renew endpoint
  config/routes.rb
  spec/requests/waste_carriers_engine/renews_spec.rb
Labels: enhancement

#901 Hide contact name, phone and email in renewals
  app/models/concerns/waste_carriers_engine/can_copy_data_from_registration.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  spec/factories/renewing_registration.rb
  spec/fixtures/files/request_to_worldpay.xml
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
Labels: enhancement

#902 Don't copy account email around editing
  app/models/waste_carriers_engine/edit_registration.rb
  app/services/waste_carriers_engine/edit_completion_service.rb
  spec/models/waste_carriers_engine/edit_registration_spec.rb
  spec/requests/waste_carriers_engine/edit_complete_forms_spec.rb
  spec/services/waste_carriers_engine/edit_completion_service_spec.rb
Labels: bug
