Repository DEFRA/waste-carriers-engine, pull requests merged in 2020-04, with the labels that each got.

#770 Fix W3C fail with tel. no. on reg. complete page
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  config/locales/forms/registration_completed_forms/en.yml
Labels: bug

#773 Update text on 'application received' pages
  config/locales/forms/registration_received_pending_conviction_forms/en.yml
  config/locales/forms/renewal_received_forms/en.yml
Labels: enhancement

#772 Add missing smart answers answer to check your answers page
  app/views/waste_carriers_engine/check_your_answers_forms/new.html.erb
  config/locales/forms/check_your_answers_forms/en.yml
Labels: enhancement

#771 Update text on contact postcode form
  config/locales/forms/contact_postcode_forms/en.yml
Labels: enhancement

#767 Add renewal number lookup page
  app/controllers/waste_carriers_engine/renew_registration_forms_controller.rb
  app/forms/waste_carriers_engine/renew_registration_form.rb
  app/models/waste_carriers_engine/new_registration.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/validators/waste_carriers_engine/renewal_lookup_validator.rb
  app/views/waste_carriers_engine/renew_registration_forms/new.html.erb
  config/locales/forms/renew_registration_forms/en.yml
  spec/requests/waste_carriers_engine/renew_registration_forms_spec.rb
  spec/validators/waste_carriers_engine/renewal_lookup_validators_spec.rb
Labels: enhancement

#774 Update completion screens to reflect changes to the wireframe
  app/views/shared/_contact_environment_agency.html.erb
  app/views/shared/_link_to_survey.html.erb
  app/views/shared/_registration_checks.html.erb
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_conviction_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_payment_forms/new.html.erb
  config/locales/forms/registration_completed_forms/en.yml
  config/locales/forms/registration_received_pending_conviction_forms/en.yml
  config/locales/forms/registration_received_pending_payment_forms/en.yml
  config/locales/shared/contact_environment_agency.en.yml
  config/locales/shared/link_to_survey.en.yml
  config/locales/shared/registration_checks.en.yml
Labels: enhancement

#775 Do not copy relevant people unless declared convictions
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/concerns/waste_carriers_engine/can_limit_number_of_relevant_people.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/models/concerns/waste_carriers_engine/can_use_renewing_registration_workflow.rb
  app/services/waste_carriers_engine/conviction_data_service.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/views/waste_carriers_engine/check_your_answers_forms/new.html.erb
  spec/factories/new_registration.rb
  spec/requests/waste_carriers_engine/registration_completed_forms_spec.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: bug

#776 Remove full stop from heading
  config/locales/forms/registration_received_pending_conviction_forms/en.yml
Labels: bug

#778 Update text to match wireframe
  config/locales/shared/contact_environment_agency.en.yml
Labels: enhancement

#777 Add check your tier screen to new registration flow
  app/controllers/waste_carriers_engine/check_your_tier_forms_controller.rb
  app/forms/waste_carriers_engine/check_your_tier_form.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/models/waste_carriers_engine/new_registration.rb
  app/views/shared/_what_are_lower_and_upper_tier.html.erb
  app/views/waste_carriers_engine/check_your_tier_forms/new.html.erb
  app/views/waste_carriers_engine/your_tier_forms/new.html.erb
  config/locales/forms/check_your_tier_forms/en.yml
  config/locales/forms/your_tier_forms/en.yml
  config/locales/shared/what_are_lower_and_upper_tier.en.yml
  config/routes.rb
  spec/models/waste_carriers_engine/new_registration_workflow/business_type_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/check_your_tier_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/other_businesses_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/your_tier_form_spec.rb
  spec/requests/waste_carriers_engine/check_your_tier_forms_spec.rb
Labels: enhancement

#780 Do not copy new temp attribute to registration
  app/services/waste_carriers_engine/registration_completion_service.rb
  spec/factories/new_registration.rb
Labels: bug

#781 Update content of completed registration email
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.html.erb
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.txt.erb
  config/locales/mailers/new_registration_mailer.en.yml
Labels: enhancement

#785 Update VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#787 Update workflow on new registration
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/models/waste_carriers_engine/new_registration_workflow/cbd_type_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/check_your_tier_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_name_form_spec.rb
Labels: enhancement

#788 Add id to reg identifier spans on completed pages
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_conviction_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_payment_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_complete_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_received_forms/new.html.erb
Labels: enhancement

#789 Make minor tweaks to lower tier new reg confirmation email
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.html.erb
  config/locales/mailers/new_registration_mailer.en.yml
Labels: bug

#786 Send email when user registers and has pending payment
  app/mailers/waste_carriers_engine/new_registration_mailer.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_payment.html.erb
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_payment.txt.erb
  config/locales/mailers/new_registration_mailer.en.yml
  spec/factories/new_registration.rb
  spec/mailers/waste_carriers_engine/new_registration_mailer_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
Labels: enhancement

#791 Fix flow for overseas businesses
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/models/waste_carriers_engine/new_registration_workflow/check_your_tier_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/location_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/other_businesses_form_spec.rb
Labels: bug

#792 Do not show result of smart answers if the user knew their tier
  app/controllers/waste_carriers_engine/check_your_answers_forms_controller.rb
  app/models/waste_carriers_engine/new_registration.rb
  app/presenters/waste_carriers_engine/check_your_answers_form_presenter.rb
  app/views/waste_carriers_engine/check_your_answers_forms/new.html.erb
  spec/models/waste_carriers_engine/new_registration_spec.rb
  spec/presenters/waste_carriers_engine/check_your_answers_form_presenter_spec.rb
Labels: enhancement

#793 Add missing ID to renewal start page
  app/views/waste_carriers_engine/renew_registration_forms/new.html.erb
Labels: bug

#795 Fix style of registration activated email as per wireframe
  app/services/waste_carriers_engine/registration_activation_service.rb
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.html.erb
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.txt.erb
  config/locales/mailers/new_registration_mailer.en.yml
Labels: enhancement

#794 Fix alignment of email content
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_payment.html.erb
Labels: bug

#796 Add scopes to fetch active and expired registrations in grace window
  app/models/waste_carriers_engine/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: enhancement

#797 Send email when new reg application is pending conviction check
  app/mailers/waste_carriers_engine/new_registration_mailer.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_conviction_check.html.erb
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_conviction_check.txt.erb
  config/locales/mailers/new_registration_mailer.en.yml
  spec/mailers/waste_carriers_engine/new_registration_mailer_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
Labels: enhancement

#798 Fix SSCL email address
  config/locales/forms/bank_transfer_forms/en.yml
  config/locales/forms/copy_cards_bank_transfer_forms/en.yml
  config/locales/forms/shared/bank_transfer_details.en.yml
  config/locales/mailers/new_registration_mailer.en.yml
  config/locales/mailers/order_copy_cards_mailer.en.yml
  config/locales/mailers/renewal_mailer.en.yml
Labels: bug

#800 Refresh VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#799 Update text as per wireframe changes
  config/locales/mailers/new_registration_mailer.en.yml
Labels: enhancement

#801 Update scope to not include last day of grace window
  app/models/waste_carriers_engine/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: bug

#805 Move and rename renewing registration workflow specs
  spec/models/waste_carriers_engine/renewing_registration_workflow/bank_transfer_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/business_type_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cannot_renew_lower_tier_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cannot_renew_type_change_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cards_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cbd_type_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/check_your_answers_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/company_address_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/company_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/company_name_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/company_postcode_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/construction_demolition_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_address_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_email_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_name_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_phone_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_postcode_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/conviction_details_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/declaration_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/declare_convictions_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/location_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/main_people_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/other_businesses_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/payment_summary_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/register_in_northern_ireland_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/register_in_scotland_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/register_in_wales_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/registration_number_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_complete_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_information_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_received_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_start_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/service_provided_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/tier_check_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/waste_types_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/worldpay_form_spec.rb
Labels: housekeeping

#804 Refactor copy cards workflow specs to use shared examples
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_bank_transfer_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_payment_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/wordpay_form_spec.rb
Labels: housekeeping

#803 Refactor cease or revoke workflow specs to use shared examples
  spec/models/waste_carriers_engine/ceased_or_revoked_registration_workflow/cease_or_revoke_form_spec.rb
  spec/models/waste_carriers_engine/ceased_or_revoked_registration_workflow/ceased_or_revoked_confirm_form_spec.rb
Labels: housekeeping

#802 Swap shared examples for edit workflow tests
  spec/models/waste_carriers_engine/edit_registration_workflow/cbd_type_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/company_name_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/confirm_edit_cancelled_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_email_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_name_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_phone_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/edit_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/main_people_form_spec.rb
  spec/support/shared_examples/workflow_states/a_simple_bidirectional_transition.rb
  spec/support/shared_examples/workflow_states/a_simple_monodirectional_transition.rb
Labels: housekeeping

#807 Remove = in Travis rubocop command
  .travis.yml
Labels: housekeeping

#809 Add configs for defra ruby address gem
  Gemfile.lock
  lib/waste_carriers_engine.rb
  lib/waste_carriers_engine/engine.rb
  spec/dummy/config/initializers/waste_carriers_engine.rb
  waste_carriers_engine.gemspec
Labels: enhancement

#810 Refactor renewal workflow specs to use next and back shared examples
  spec/models/waste_carriers_engine/renewing_registration_workflow/bank_transfer_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/business_type_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cannot_renew_lower_tier_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cannot_renew_type_change_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cards_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/cbd_type_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/check_your_answers_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/company_name_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/construction_demolition_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_email_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_name_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_phone_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/conviction_details_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/declaration_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/declare_convictions_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/location_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/main_people_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/other_businesses_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/payment_summary_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/register_in_northern_ireland_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/register_in_scotland_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/register_in_wales_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/registration_number_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_information_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_start_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/service_provided_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/tier_check_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/waste_types_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/worldpay_form_spec.rb
Labels: housekeeping

#811 Factory-generated renewals always initialise with registration
  spec/factories/renewing_registration.rb
Labels: housekeeping

#812 Use fixed final state workflow examples for renewals
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_complete_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_received_form_spec.rb
Labels: housekeeping

#813 Use shared examples for renewal address workflow specs
  spec/models/waste_carriers_engine/renewing_registration_workflow/company_address_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/company_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/company_postcode_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_address_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/contact_postcode_form_spec.rb
Labels: housekeeping

#814 Merge repeating request specs
  spec/requests/waste_carriers_engine/bank_transfer_forms_spec.rb
  spec/requests/waste_carriers_engine/business_type_forms_spec.rb
  spec/requests/waste_carriers_engine/cannot_renew_company_no_change_forms_spec.rb
  spec/requests/waste_carriers_engine/cannot_renew_lower_tier_forms_spec.rb
  spec/requests/waste_carriers_engine/cannot_renew_type_change_forms_spec.rb
  spec/requests/waste_carriers_engine/cards_forms_spec.rb
  spec/requests/waste_carriers_engine/cbd_type_forms_spec.rb
  spec/requests/waste_carriers_engine/check_your_answers_forms_spec.rb
  spec/requests/waste_carriers_engine/check_your_tier_forms_spec.rb
  spec/requests/waste_carriers_engine/company_address_forms_spec.rb
  spec/requests/waste_carriers_engine/company_address_manual_forms_spec.rb
  spec/requests/waste_carriers_engine/company_name_forms_spec.rb
  spec/requests/waste_carriers_engine/company_postcode_forms_spec.rb
  spec/requests/waste_carriers_engine/construction_demolition_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_address_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_address_manual_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_email_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_name_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_phone_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_postcode_forms_spec.rb
  spec/requests/waste_carriers_engine/conviction_details_forms_spec.rb
  spec/requests/waste_carriers_engine/copy_cards_bank_transfer_forms_spec.rb
  spec/requests/waste_carriers_engine/declaration_forms_spec.rb
  spec/requests/waste_carriers_engine/declare_convictions_forms_spec.rb
  spec/requests/waste_carriers_engine/edit_bank_transfer_forms_spec.rb
  spec/requests/waste_carriers_engine/edit_payment_summary_forms_spec.rb
  spec/requests/waste_carriers_engine/errors_spec.rb
  spec/requests/waste_carriers_engine/location_forms_spec.rb
  spec/requests/waste_carriers_engine/main_people_forms_spec.rb
  spec/requests/waste_carriers_engine/other_businesses_forms_spec.rb
  spec/requests/waste_carriers_engine/payment_summary_forms_spec.rb
  spec/requests/waste_carriers_engine/register_in_northern_ireland_forms_spec.rb
  spec/requests/waste_carriers_engine/register_in_scotland_forms_spec.rb
  spec/requests/waste_carriers_engine/register_in_wales_forms_spec.rb
  spec/requests/waste_carriers_engine/registration_number_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_complete_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_information_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_start_forms_spec.rb
  spec/requests/waste_carriers_engine/service_provided_forms_spec.rb
  spec/requests/waste_carriers_engine/tier_check_forms_spec.rb
  spec/requests/waste_carriers_engine/waste_types_forms_spec.rb
  spec/requests/waste_carriers_engine/worldpay_forms_spec.rb
  spec/support/shared_examples/post_renewal_form.rb
  spec/support/shared_examples/post_without_params_form.rb
  spec/support/shared_examples/request_get_flexible_form.rb
  spec/support/shared_examples/request_get_locked_in_form.rb
Labels: housekeeping

#816 Add new address lookup service and refactor
  app/forms/waste_carriers_engine/address_lookup_form_base.rb
  app/services/waste_carriers_engine/address_finder_service.rb
  app/services/waste_carriers_engine/address_lookup_service.rb
  app/validators/waste_carriers_engine/postcode_validator.rb
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/forms/waste_carriers_engine/company_postcode_forms_spec.rb
  spec/forms/waste_carriers_engine/contact_postcode_forms_spec.rb
  spec/requests/waste_carriers_engine/company_postcode_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_postcode_forms_spec.rb
  spec/services/waste_carriers_engine/address_finder_service_spec.rb
  spec/services/waste_carriers_engine/address_lookup_service_spec.rb
  spec/support/address_finder_service_stub_helper.rb
  spec/support/shared_examples/validate_postcode.rb
Labels: enhancement

#817 Remove VCR and use Webmock instead
  Gemfile
  Gemfile.lock
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
  spec/fixtures/worldpay_initial_request.xml
  spec/fixtures/worldpay_initial_request_invalid.xml
  spec/fixtures/worldpay_redirect.xml
  spec/forms/waste_carriers_engine/contact_address_forms_spec.rb
  spec/requests/waste_carriers_engine/worldpay_forms_spec.rb
  spec/services/waste_carriers_engine/worldpay_service_spec.rb
  spec/support/vcr.rb
Labels: housekeeping

#818 Add scope to filter out ad registrations
  app/models/waste_carriers_engine/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: bug

#819 Revert "Add scope to filter out ad registrations"
  app/models/waste_carriers_engine/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: bug

#821 Add bank transfer details to new reg completion screen
  app/views/waste_carriers_engine/registration_received_pending_payment_forms/new.html.erb
  app/views/waste_carriers_engine/shared/_bank_transfer_email_details.html.erb
  config/locales/forms/registration_received_pending_payment_forms/en.yml
  config/locales/forms/shared/bank_transfer_email_details.en.yml
Labels: enhancement
