Repository DEFRA/waste-carriers-engine, pull requests merged in 2020-01, with the labels that each got.

#630 Add constant for payment types and scope for refund
  app/models/waste_carriers_engine/payment.rb
  spec/models/waste_carriers_engine/payment_spec.rb
Labels: enhancement, housekeeping

#631 Add payment types methods and default currency
  app/models/concerns/waste_carriers_engine/can_have_payment_type.rb
  app/models/waste_carriers_engine/payment.rb
  spec/models/waste_carriers_engine/payment_spec.rb
  spec/support/shared_examples/can_have_payment_type.rb
Labels: enhancement, housekeeping

#632 Externalise Worldpay code into concerns
  app/services/concerns/waste_carriers_engine/can_build_worldpay_xml.rb
  app/services/concerns/waste_carriers_engine/can_send_worldpay_request.rb
  app/services/waste_carriers_engine/worldpay_service.rb
  app/services/waste_carriers_engine/worldpay_xml_service.rb
Labels: enhancement

#633 Fix translations for ceased registrations
  app/controllers/waste_carriers_engine/ceased_or_revoked_confirm_forms_controller.rb
  config/locales/forms/ceased_or_revoked_confirm_forms/en.yml
Labels: bug

#634 Redirect to correct back office dashboard
  app/controllers/waste_carriers_engine/ceased_or_revoked_confirm_forms_controller.rb
  spec/requests/waste_carriers_engine/ceased_or_revoked_confirm_forms_spec.rb
Labels: bug

#635 Fix pluralisation in copy cards mailer subject
  config/locales/mailers/order_copy_cards_mailer.en.yml
  spec/mailers/waste_carriers_engine/order_copy_cards_mailer_spec.rb
Labels: bug

#636 Add partial for error flash messages
  app/views/shared/_error.html.erb
Labels: enhancement

#638 Update VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#639 Remove log of worldpay
  app/services/concerns/waste_carriers_engine/can_send_worldpay_request.rb
Labels: bug

#640 Add missing page titles
  config/locales/forms/cease_or_revoke_forms/en.yml
  config/locales/forms/ceased_or_revoked_confirm_forms/en.yml
  config/locales/forms/copy_cards_bank_transfer_forms/en.yml
  config/locales/forms/copy_cards_forms/en.yml
  config/locales/forms/copy_cards_order_completed_forms/en.yml
  config/locales/forms/copy_cards_payment_forms/en.yml
Labels: bug

#642 Add excess amount method to finance details
  app/models/waste_carriers_engine/finance_details.rb
  spec/models/waste_carriers_engine/finance_details_spec.rb
Labels: enhancement

#643 Add #zero_difference_balance method to FinanceDetails
  app/models/waste_carriers_engine/finance_details.rb
  spec/models/waste_carriers_engine/finance_details_spec.rb
Labels: enhancement

#644 Fix bug on redirect after error
  app/services/concerns/waste_carriers_engine/can_send_worldpay_request.rb
Labels: bug

#647 Fix broken 'Finished' link on renewal end pages
  app/controllers/waste_carriers_engine/renewal_complete_forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_received_forms_controller.rb
  app/helpers/waste_carriers_engine/application_helper.rb
  app/helpers/waste_carriers_engine/journey_links_helper.rb
  app/views/waste_carriers_engine/renewal_complete_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_received_forms/new.html.erb
  config/locales/en.yml
  spec/helpers/waste_carriers_engine/application_helper_spec.rb
  spec/helpers/waste_carriers_engine/journey_links_helper_spec.rb
Labels: bug

#649 Set unique order key for non-worldpay payments
  app/models/waste_carriers_engine/payment.rb
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
  spec/models/waste_carriers_engine/payment_spec.rb
Labels: bug

#651 Temp. fix for cc-test-reporter & SimpleCov 0.18
  Gemfile
  Gemfile.lock
Labels: housekeeping

#652 Fix changelog generator
  lib/tasks/changelog.rake
Labels: housekeeping
