Repository DEFRA/waste-carriers-engine, pull requests merged in 2020-03, with the labels that each got.

#696 Remove user authentication from base form controller
  app/controllers/waste_carriers_engine/cease_or_revoke_forms_controller.rb
  app/controllers/waste_carriers_engine/copy_cards_forms_controller.rb
  app/controllers/waste_carriers_engine/edit_forms_controller.rb
  app/controllers/waste_carriers_engine/forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_start_forms_controller.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/services/waste_carriers_engine/blank_permission_check_service.rb
  app/services/waste_carriers_engine/flow_permission_checks_service.rb
  spec/requests/waste_carriers_engine/ceased_or_revoked_confirm_forms_spec.rb
  spec/requests/waste_carriers_engine/copy_cards_payment_forms_spec.rb
  spec/services/waste_carriers_engine/blank_permission_check_service_spec.rb
  spec/services/waste_carriers_engine/flow_permission_checks_service_spec.rb
Labels: enhancement, housekeeping

#695 Add start form for new registrations
  app/controllers/waste_carriers_engine/forms_controller.rb
  app/controllers/waste_carriers_engine/renew_registration_forms_controller.rb
  app/controllers/waste_carriers_engine/start_forms_controller.rb
  app/forms/waste_carriers_engine/base_form.rb
  app/forms/waste_carriers_engine/renew_registration_form.rb
  app/forms/waste_carriers_engine/start_form.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/models/waste_carriers_engine/new_registration.rb
  app/views/waste_carriers_engine/renew_registration_forms/new.html.erb
  app/views/waste_carriers_engine/start_forms/new.html.erb
  config/locales/forms/start_forms/en.yml
  config/routes.rb
  spec/factories/forms/start_form.rb
  spec/forms/waste_carriers_engine/base_forms_spec.rb
  spec/forms/waste_carriers_engine/start_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/location_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/renew_registration_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/start_form_spec.rb
  spec/requests/waste_carriers_engine/start_forms_spec.rb
Labels: enhancement

#704 Add hint to cease or revoke reason
  app/views/waste_carriers_engine/cease_or_revoke_forms/new.html.erb
  config/locales/forms/cease_or_revoke_forms/en.yml
Labels: enhancement

#703 Build new registration workflow for Upper tier
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/models/waste_carriers_engine/new_registration_workflow/business_type_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/cards_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/cbd_type_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/check_your_answers_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_address_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_name_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_postcode_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/construction_demolition_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/contact_address_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/contact_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/contact_email_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/contact_name_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/contact_phone_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/contact_postcode_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/conviction_details_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/declaration_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/declare_convictions_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/location_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/main_people_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/other_businesses_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/payment_summary_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/register_in_northern_ireland_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/register_in_scotland_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/register_in_wales_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/registration_number_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/renew_registration_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/service_provided_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/start_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/waste_types_form_spec.rb
  spec/requests/waste_carriers_engine/business_type_forms_spec.rb
  spec/requests/waste_carriers_engine/cards_forms_spec.rb
  spec/requests/waste_carriers_engine/cbd_type_forms_spec.rb
  spec/requests/waste_carriers_engine/company_name_forms_spec.rb
  spec/requests/waste_carriers_engine/construction_demolition_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_email_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_name_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_phone_forms_spec.rb
  spec/requests/waste_carriers_engine/declaration_forms_spec.rb
  spec/requests/waste_carriers_engine/declare_convictions_forms_spec.rb
  spec/requests/waste_carriers_engine/location_forms_spec.rb
  spec/requests/waste_carriers_engine/other_businesses_forms_spec.rb
  spec/requests/waste_carriers_engine/payment_summary_forms_spec.rb
  spec/requests/waste_carriers_engine/service_provided_forms_spec.rb
  spec/requests/waste_carriers_engine/waste_types_forms_spec.rb
  spec/support/shared_examples/post_form.rb
  spec/support/shared_examples/post_renewal_form.rb
  spec/support/shared_examples/workflow_states/a_manual_address_transition.rb
  spec/support/shared_examples/workflow_states/a_simple_monodirectional_transition.rb
  spec/support/shared_examples/workflow_states/an_address_lookup_transition.rb
  spec/support/shared_examples/workflow_states/has_back_transition.rb
  spec/support/shared_examples/workflow_states/has_next_transition.rb
Labels: enhancement

#705 Externalise tiers in their own concern
  app/models/concerns/waste_carriers_engine/can_generate_reg_identifier.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/concerns/waste_carriers_engine/can_have_tier.rb
  app/models/waste_carriers_engine/registration.rb
Labels: housekeeping

#708 Fix matching comp. reg. no's with lowercase chars
  app/models/waste_carriers_engine/renewing_registration.rb
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
Labels: bug

#706 Set Lower Tier and Upper tier in new registration journey
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/factories/new_registration.rb
  spec/models/waste_carriers_engine/new_registration_workflow/business_type_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_name_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/construction_demolition_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/waste_types_form_spec.rb
Labels: enhancement

#710 Implement forks for lower tier new registration journey
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/models/waste_carriers_engine/new_registration_workflow/contact_name_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/declaration_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/main_people_form_spec.rb
Labels: enhancement

#711 Update cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#707 Add locking to MongoId documents
  Gemfile
  Gemfile.lock
  app/controllers/waste_carriers_engine/worldpay_forms_controller.rb
  app/models/concerns/waste_carriers_engine/can_use_lock.rb
  app/models/waste_carriers_engine/new_registration.rb
  app/models/waste_carriers_engine/past_registration.rb
  app/models/waste_carriers_engine/registration.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  spec/requests/waste_carriers_engine/worldpay_forms_spec.rb
  spec/services/waste_carriers_engine/renewal_completion_service_spec.rb
Labels: enhancement

#712 Remove business owner screen from Lower Tier journey
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_address_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/contact_name_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/main_people_form_spec.rb
Labels: enhancement

#713 Add translations for charity business type
  config/locales/forms/check_your_answers_forms/en.yml
  config/locales/forms/company_address_forms/en.yml
  config/locales/forms/company_address_manual_forms/en.yml
  config/locales/forms/company_name_forms/en.yml
  config/locales/forms/company_postcode_forms/en.yml
  config/locales/forms/edit_forms/en.yml
Labels: enhancement

#714 Switch to SonarCloud from CodeClimate
  .travis.yml
  README.md
  sonar-project.properties
Labels: housekeeping

#715 Add mongoid-locker to list of dependency
  Gemfile.lock
  waste_carriers_engine.gemspec
Labels: enhancement

#716 Fix Mongoid::Locker dependency
  lib/waste_carriers_engine/engine.rb
Labels: bug

#717 Actually fix mongoid-locker dependency
  lib/waste_carriers_engine/engine.rb
Labels: bug

#718 Hide start new registration behind feature toggle
  config/routes.rb
  spec/requests/waste_carriers_engine/start_forms_spec.rb
Labels: housekeeping

#722 Add lock to transient objects using worldpay payments
  app/models/waste_carriers_engine/edit_registration.rb
  app/models/waste_carriers_engine/order_copy_cards_registration.rb
Labels: bug

#723 Fix rails bin scripts (rails console)
  bin/rails
  spec/dummy/bin/rails
Labels: bug

#720 Generate unique identifier number on declaration page
  app/forms/waste_carriers_engine/declaration_form.rb
  app/models/concerns/waste_carriers_engine/can_generate_reg_identifier.rb
  app/models/waste_carriers_engine/counter.rb
  app/models/waste_carriers_engine/registration.rb
  app/services/waste_carriers_engine/generate_reg_identifier_service.rb
  spec/factories/counter.rb
  spec/factories/forms/declaration_form.rb
  spec/factories/registration.rb
  spec/forms/waste_carriers_engine/declaration_forms_spec.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/services/waste_carriers_engine/generate_reg_identifier_service_spec.rb
Labels: enhancement

#719 Implement new Check your answers page
  .travis.yml
  app/controllers/waste_carriers_engine/check_your_answers_forms_controller.rb
  app/forms/waste_carriers_engine/check_your_answers_form.rb
  app/forms/waste_carriers_engine/main_people_form.rb
  app/models/concerns/waste_carriers_engine/can_limit_number_of_main_people.rb
  app/presenters/waste_carriers_engine/base_presenter.rb
  app/presenters/waste_carriers_engine/check_your_answers_form_presenter.rb
  app/views/waste_carriers_engine/check_your_answers_forms/new.html.erb
  config/locales/forms/check_your_answers_forms/en.yml
  spec/dummy/config/application.rb
  spec/presenters/waste_carriers_engine/check_your_answers_form_presenter_spec.rb
Labels: enhancement

#725 Fix back flow for new registrations
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/models/waste_carriers_engine/new_registration_workflow/cbd_type_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_name_form_spec.rb
Labels: bug

#726 Use sequence to generate reg_identifier
  spec/factories/registration.rb
Labels: bug

#727 Update text to Cards page
  app/views/waste_carriers_engine/cards_forms/new.html.erb
  config/locales/forms/cards_forms/en.yml
Labels: enhancement

#728 Do not update a transient registration unless is persisted
  app/controllers/waste_carriers_engine/forms_controller.rb
Labels: bug

#730 Refactor payment summary to work with New registrations
  app/controllers/waste_carriers_engine/check_your_answers_forms_controller.rb
  app/controllers/waste_carriers_engine/payment_summary_forms_controller.rb
  app/forms/waste_carriers_engine/payment_summary_form.rb
  app/models/waste_carriers_engine/new_registration.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  app/models/waste_carriers_engine/transient_registration.rb
  app/presenters/waste_carriers_engine/resource_type_form_presenter.rb
  app/views/waste_carriers_engine/payment_summary_forms/new.html.erb
  config/locales/forms/payment_summary_forms/en.yml
  spec/presenters/waste_carriers_engine/resource_type_form_presenter_spec.rb
Labels: enhancement

#729 Fix more back flow issues
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_name_form_spec.rb
Labels: bug

#732 Calculate Reg identifier for new registrations on the fly
  app/models/waste_carriers_engine/new_registration.rb
  spec/forms/waste_carriers_engine/declaration_forms_spec.rb
  spec/models/waste_carriers_engine/new_registration_spec.rb
Labels: enhancement

#731 Update pay by bank transfer screen to reflect changes to the wireframe
  app/models/waste_carriers_engine/new_registration.rb
  app/views/waste_carriers_engine/bank_transfer_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_mailer/send_renewal_received_pending_payment_email.html.erb
  config/locales/forms/bank_transfer_forms/en.yml
  config/locales/mailers/renewal_mailer.en.yml
Labels: enhancement

#734 Add presenter for order details
  app/presenters/waste_carriers_engine/order_and_total_presenter.rb
  config/locales/shared/order_and_total.en.yml
  spec/presenters/waste_carriers_engine/order_and_total_presenter_spec.rb
Labels: enhancement

#735 Move checks on registration type changes to concern
  app/models/concerns/waste_carriers_engine/can_check_if_registration_type_changed.rb
  app/models/waste_carriers_engine/edit_registration.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  spec/models/waste_carriers_engine/edit_registration_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
  spec/support/shared_examples/can_check_if_registration_type_changed.rb
Labels: enhancement

#736 Make EditCompletionService deal with new finance info
  app/services/waste_carriers_engine/edit_completion_service.rb
  spec/services/waste_carriers_engine/edit_completion_service_spec.rb
Labels: enhancement

#733 Set up order models for type change during edit
  app/models/waste_carriers_engine/order.rb
  app/models/waste_carriers_engine/order_item.rb
  app/services/waste_carriers_engine/order_additional_cards_service.rb
  config/locales/order_items.en.yml
  spec/models/waste_carriers_engine/order_item_spec.rb
  spec/models/waste_carriers_engine/order_spec.rb
  spec/services/waste_carriers_engine/order_additional_cards_service_spec.rb
Labels: enhancement

#739 Fixes to check your answers validations and texts
  app/forms/waste_carriers_engine/check_your_answers_form.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  config/locales/forms/check_your_answers_forms/en.yml
Labels: enhancement

#737 Build finance_details object for edit journey
  app/models/waste_carriers_engine/order_copy_cards_registration.rb
  app/services/waste_carriers_engine/build_edit_finance_details_service.rb
  app/services/waste_carriers_engine/build_order_copy_cards_finance_details_service.rb
  spec/services/waste_carriers_engine/build_edit_finance_details_service_spec.rb
  spec/services/waste_carriers_engine/build_order_copy_cards_finance_details_service_spec.rb
Labels: enhancement

#742 Rename RegistrationCompletionService to RegistrationActivationService
  app/services/waste_carriers_engine/registration_activation_service.rb
  spec/services/waste_carriers_engine/registration_activation_service_spec.rb
Labels: enhancement

#743 Generate a new registration on completion with pending payments
  app/controllers/waste_carriers_engine/declaration_forms_controller.rb
  app/controllers/waste_carriers_engine/registration_received_pending_payment_forms_controller.rb
  app/forms/waste_carriers_engine/registration_received_pending_payment_form.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/models/waste_carriers_engine/new_registration.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/views/waste_carriers_engine/registration_received_pending_payment_forms/new.html.erb
  config/locales/forms/registration_received_pending_payment_forms/en.yml
  config/routes.rb
  spec/factories/new_registration.rb
  spec/models/waste_carriers_engine/new_registration_workflow/bank_transfer_form_spec.rb
  spec/requests/waste_carriers_engine/registration_received_pending_payment_forms_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
Labels: enhancement

#747 Show the user a completed screen for conviction checks required
  app/controllers/waste_carriers_engine/registration_received_pending_conviction_forms_controller.rb
  app/forms/waste_carriers_engine/registration_received_pending_conviction_form.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/views/waste_carriers_engine/registration_received_pending_conviction_forms/new.html.erb
  config/locales/forms/registration_received_pending_conviction_forms/en.yml
  config/routes.rb
  spec/factories/new_registration.rb
  spec/models/waste_carriers_engine/new_registration_workflow/worldpay_form_spec.rb
  spec/requests/waste_carriers_engine/registration_received_pending_conviction_forms_spec.rb
Labels: enhancement

#741 Set up workflow for edit payments by bank transfer
  app/controllers/waste_carriers_engine/edit_bank_transfer_forms_controller.rb
  app/controllers/waste_carriers_engine/edit_payment_summary_forms_controller.rb
  app/forms/waste_carriers_engine/edit_bank_transfer_form.rb
  app/forms/waste_carriers_engine/edit_payment_summary_form.rb
  app/models/concerns/waste_carriers_engine/can_use_edit_registration_workflow.rb
  app/models/waste_carriers_engine/edit_registration.rb
  app/services/waste_carriers_engine/build_edit_finance_details_service.rb
  app/views/waste_carriers_engine/edit_bank_transfer_forms/new.html.erb
  app/views/waste_carriers_engine/edit_payment_summary_forms/new.html.erb
  app/views/waste_carriers_engine/shared/_bank_transfer_details.html.erb
  app/views/waste_carriers_engine/shared/_order_and_total.html.erb
  app/views/waste_carriers_engine/shared/_payment_summary_options.html.erb
  config/locales/forms/edit_bank_transfer_forms/en.yml
  config/locales/forms/edit_payment_summary_forms/en.yml
  config/locales/forms/shared/bank_transfer_details.en.yml
  config/locales/forms/shared/order_and_total.en.yml
  config/locales/forms/shared/payment_summary_options.en.yml
  config/routes.rb
  spec/factories/edit_registration.rb
  spec/factories/finance_details.rb
  spec/factories/forms/copy_cards_bank_transfer_form.rb
  spec/factories/forms/edit_bank_transfer_form.rb
  spec/factories/forms/edit_payment_summary_form.rb
  spec/factories/order.rb
  spec/forms/waste_carriers_engine/edit_bank_transfer_forms_spec.rb
  spec/forms/waste_carriers_engine/edit_payment_summary_forms_spec.rb
  spec/models/waste_carriers_engine/edit_registration_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/declaration_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/edit_bank_transfer_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/edit_payment_summary_form_spec.rb
  spec/requests/waste_carriers_engine/edit_bank_transfer_forms_spec.rb
  spec/requests/waste_carriers_engine/edit_payment_summary_forms_spec.rb
  spec/services/waste_carriers_engine/build_edit_finance_details_service_spec.rb
Labels: enhancement

#748 Add completed registration screen
  app/controllers/waste_carriers_engine/registration_completed_forms_controller.rb
  app/forms/waste_carriers_engine/registration_completed_form.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  config/initializers/date_formats.rb
  config/locales/forms/registration_completed_forms/en.yml
  config/routes.rb
  spec/models/waste_carriers_engine/new_registration_workflow/worldpay_form_spec.rb
  spec/requests/waste_carriers_engine/registration_completed_forms_spec.rb
Labels: enhancement

#751 Add rules to completed screen for lower tier registrations
  app/services/waste_carriers_engine/registration_activation_service.rb
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  config/locales/forms/registration_completed_forms/en.yml
  spec/factories/new_registration.rb
  spec/requests/waste_carriers_engine/registration_completed_forms_spec.rb
Labels: enhancement

#755 Refresh VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#753 Make declaration error message more generic
  config/locales/forms/declaration_forms/en.yml
Labels: enhancement

#752 Only merge finance details if reg type has changed in edit
  app/services/waste_carriers_engine/edit_completion_service.rb
  spec/services/waste_carriers_engine/edit_completion_service_spec.rb
Labels: bug

#754 Fix edit redirect URLs
  config/routes.rb
Labels: bug

#756 Backfill individual DOB fields when initialising key person
  app/models/waste_carriers_engine/key_person.rb
  spec/models/waste_carriers_engine/key_person_spec.rb
Labels: bug

#757 Remove extra email from completion page
  app/views/waste_carriers_engine/registration_received_pending_payment_forms/new.html.erb
Labels: bug

#758 Edit registration copy over order
  app/controllers/waste_carriers_engine/worldpay_forms_controller.rb
  app/services/waste_carriers_engine/edit_completion_service.rb
  spec/requests/waste_carriers_engine/edit_complete_forms_spec.rb
Labels: enhancement

#760 Edit registration - pay by worldpay
  app/models/concerns/waste_carriers_engine/can_use_edit_registration_workflow.rb
  app/services/waste_carriers_engine/worldpay_xml_service.rb
  app/views/waste_carriers_engine/edit_payment_summary_forms/new.html.erb
  app/views/waste_carriers_engine/payment_summary_forms/new.html.erb
  app/views/waste_carriers_engine/shared/_payment_errors.html.erb
  config/locales/en.yml
  config/locales/forms/payment_summary_forms/en.yml
  spec/models/waste_carriers_engine/edit_registration_workflow/edit_payment_summary_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/worldpay_form_spec.rb
Labels: enhancement

#759 Ask for business type when registration is edited from overseas to UK
  app/models/concerns/waste_carriers_engine/can_use_edit_registration_workflow.rb
  app/models/waste_carriers_engine/edit_registration.rb
  spec/models/waste_carriers_engine/edit_registration_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/business_type_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/location_form_spec.rb
Labels: bug

#763 Show the correct total charge when a renewal has a type change
  app/views/waste_carriers_engine/check_your_answers_forms/new.html.erb
Labels: bug

#762 Don't display 'stuck' tag on revoked renewals
  app/models/waste_carriers_engine/renewing_registration.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
Labels: bug

#764 Location cannot be edited
  app/models/concerns/waste_carriers_engine/can_use_edit_registration_workflow.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  config/locales/forms/edit_forms/en.yml
  config/routes.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/business_type_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/edit_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/location_form_spec.rb
  spec/requests/waste_carriers_engine/edit_forms_spec.rb
Labels: enhancement

#761 Add your tier page to new registration flow
  app/controllers/waste_carriers_engine/your_tier_forms_controller.rb
  app/forms/waste_carriers_engine/your_tier_form.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/views/waste_carriers_engine/your_tier_forms/new.html.erb
  config/locales/forms/your_tier_forms/en.yml
  config/routes.rb
  spec/models/waste_carriers_engine/new_registration_workflow/business_type_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/cbd_type_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/company_name_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/construction_demolition_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/waste_types_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/your_tier_form_spec.rb
  spec/requests/waste_carriers_engine/your_tier_forms_spec.rb
Labels: enhancement

#765 Make main people form work with old business types
  app/forms/waste_carriers_engine/main_people_form.rb
  config/locales/forms/main_people_forms/en.yml
  spec/forms/waste_carriers_engine/main_people_forms_spec.rb
Labels: bug

#766 Add missing translations for authority and public body
  config/locales/forms/company_address_forms/en.yml
  config/locales/forms/company_address_manual_forms/en.yml
  config/locales/forms/company_name_forms/en.yml
  config/locales/forms/company_postcode_forms/en.yml
  config/locales/forms/edit_forms/en.yml
Labels: bug

#768 Exclude confirmed convictions from :convictions_possible_match scope
  app/models/concerns/waste_carriers_engine/can_filter_conviction_status.rb
  spec/support/shared_examples/can_filter_conviction_status.rb
Labels: bug

#769 Fixes to lower tier registration
  app/models/concerns/waste_carriers_engine/can_change_registration_status.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/models/waste_carriers_engine/new_registration.rb
  app/models/waste_carriers_engine/order.rb
  app/services/waste_carriers_engine/build_new_registration_finance_details_service.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  spec/services/waste_carriers_engine/build_new_registration_finance_details_service_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
Labels: bug
