Repository DEFRA/waste-carriers-engine, pull requests merged in 2020-02, with the labels that each got.

#656 Add charge adjust order item type and method
  app/models/waste_carriers_engine/order_item.rb
  spec/models/waste_carriers_engine/order_item_spec.rb
Labels: enhancement

#657 Switch airbrake mgmt to defra-ruby-alert
  Gemfile
  Gemfile.lock
  lib/waste_carriers_engine.rb
  lib/waste_carriers_engine/engine.rb
  spec/dummy/config/initializers/airbrake.rb
  spec/dummy/config/initializers/waste_carriers_engine.rb
  waste_carriers_engine.gemspec
Labels: housekeeping

#658 Add scope for reversible payments
  app/models/concerns/waste_carriers_engine/can_have_payment_type.rb
  app/models/waste_carriers_engine/payment.rb
  spec/models/waste_carriers_engine/payment_spec.rb
Labels: enhancement

#660 Add granular error logging to Completion service
  app/controllers/waste_carriers_engine/renewal_complete_forms_controller.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  spec/services/waste_carriers_engine/renewal_completion_service_spec.rb
Labels: enhancement

#661 Set up EditRegistration model
  app/models/concerns/waste_carriers_engine/can_copy_data_from_registration.rb
  app/models/concerns/waste_carriers_engine/can_use_edit_registration_workflow.rb
  app/models/waste_carriers_engine/edit_registration.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  spec/factories/edit_registration.rb
  spec/models/waste_carriers_engine/edit_registration_spec.rb
Labels: enhancement

#662 Create a new EditRegistration
  app/controllers/waste_carriers_engine/edit_forms_controller.rb
  app/forms/waste_carriers_engine/edit_form.rb
  app/services/waste_carriers_engine/edit_registration_permission_checks_service.rb
  app/services/waste_carriers_engine/flow_permission_checks_service.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  config/locales/forms/edit_forms/en.yml
  config/routes.rb
  spec/dummy/app/models/ability.rb
  spec/requests/waste_carriers_engine/edit_forms_spec.rb
  spec/services/waste_carriers_engine/edit_registration_permission_checks_service_spec.rb
  spec/services/waste_carriers_engine/flow_permission_checks_service_spec.rb
Labels: enhancement

#663 Update VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
Labels: housekeeping

#665 Add edit completion workflow
  app/controllers/waste_carriers_engine/edit_complete_forms_controller.rb
  app/controllers/waste_carriers_engine/edit_forms_controller.rb
  app/forms/waste_carriers_engine/edit_complete_form.rb
  app/models/concerns/waste_carriers_engine/can_use_edit_registration_workflow.rb
  app/views/waste_carriers_engine/edit_complete_forms/new.html.erb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  config/locales/forms/edit_complete_forms/en.yml
  config/locales/forms/edit_forms/en.yml
  config/routes.rb
  spec/forms/waste_carriers_engine/edit_complete_forms_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/declaration_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/edit_complete_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/edit_form_spec.rb
  spec/requests/waste_carriers_engine/edit_complete_forms_spec.rb
  spec/requests/waste_carriers_engine/edit_forms_spec.rb
Labels: enhancement

#666 Set up edit overview page
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_addresses.scss
  app/assets/stylesheets/partials/_dates.scss
  app/assets/stylesheets/partials/_footer.scss
  app/assets/stylesheets/partials/_people.scss
  app/controllers/waste_carriers_engine/edit_forms_controller.rb
  app/presenters/waste_carriers_engine/edit_form_presenter.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  app/views/waste_carriers_engine/shared/_edit_actions.html.erb
  config/locales/forms/edit_forms/en.yml
Labels: enhancement

#670 Fix view certificate for lower tier registrations
  app/presenters/waste_carriers_engine/certificate_presenter.rb
  app/views/waste_carriers_engine/pdfs/certificate.html.erb
  config/locales/pdfs/certificate.en.yml
  spec/presenters/waste_carriers_engine/certificate_presenter_spec.rb
Labels: bug

#668 Store and display created_at for transient regs
  app/models/concerns/waste_carriers_engine/can_set_created_at.rb
  app/models/waste_carriers_engine/transient_registration.rb
  app/presenters/waste_carriers_engine/edit_form_presenter.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  config/initializers/date_formats.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
Labels: enhancement

#672 Clean up edit view for lower tier regs
  app/presenters/waste_carriers_engine/edit_form_presenter.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
Labels: enhancement

#675 Don't send confirmation email for fully AD copy card orders
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/concerns/waste_carriers_engine/can_use_order_copy_cards_workflow.rb
  app/services/waste_carriers_engine/order_copy_cards_completion_service.rb
  app/views/waste_carriers_engine/copy_cards_order_completed_forms/new.html.erb
  config/locales/forms/copy_cards_order_completed_forms/en.yml
  lib/waste_carriers_engine.rb
  spec/dummy/config/initializers/waste_carriers_engine.rb
  spec/services/waste_carriers_engine/order_copy_cards_completion_service_spec.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: bug

#674 Fix missing text values on edit page
  app/presenters/waste_carriers_engine/edit_form_presenter.rb
  config/locales/forms/edit_forms/en.yml
  spec/requests/waste_carriers_engine/edit_forms_spec.rb
Labels: bug

#676 Fix renewal text issue on certificate
  app/presenters/waste_carriers_engine/certificate_presenter.rb
  app/views/waste_carriers_engine/pdfs/certificate.html.erb
  config/locales/pdfs/certificate.en.yml
  spec/presenters/waste_carriers_engine/certificate_presenter_spec.rb
Labels: bug

#677 Refactor CertificatePresenter specs
  app/presenters/waste_carriers_engine/certificate_presenter.rb
  spec/presenters/waste_carriers_engine/certificate_presenter_spec.rb
Labels: housekeeping

#673 Set up edit workflow
  app/controllers/waste_carriers_engine/edit_forms_controller.rb
  app/models/concerns/waste_carriers_engine/can_use_edit_registration_workflow.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  config/routes.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/cbd_type_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/company_address_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/company_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/company_name_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/company_postcode_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_address_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_address_manual_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_email_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_name_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_phone_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/contact_postcode_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/edit_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/location_form_spec.rb
  spec/models/waste_carriers_engine/edit_registration_workflow/main_people_form_spec.rb
  spec/requests/waste_carriers_engine/edit_forms_spec.rb
  spec/support/helpers/workflow_states.rb
  spec/support/shared_examples/workflow_states/a_manual_address_transition.rb
  spec/support/shared_examples/workflow_states/a_postcode_transition.rb
  spec/support/shared_examples/workflow_states/a_simple_monodirectional_transition.rb
  spec/support/shared_examples/workflow_states/an_address_lookup_transition.rb
Labels: enhancement

#679 Add 'back' link to edit form
  app/views/waste_carriers_engine/edit_forms/new.html.erb
Labels: bug

#678 Improve certificates for lower tier sole traders and partnerships
  app/presenters/waste_carriers_engine/certificate_presenter.rb
  spec/presenters/waste_carriers_engine/certificate_presenter_spec.rb
Labels: bug

#683 Add defra-ruby-email to project
  Gemfile.lock
  config/routes.rb
  lib/waste_carriers_engine.rb
  lib/waste_carriers_engine/engine.rb
  waste_carriers_engine.gemspec
Labels: enhancement

#684 Always use source reg's account_email during edit
  app/models/waste_carriers_engine/edit_registration.rb
  app/presenters/waste_carriers_engine/edit_form_presenter.rb
  spec/models/waste_carriers_engine/edit_registration_spec.rb
Labels: bug

#685 Display time edit was started and last modified
  app/presenters/waste_carriers_engine/edit_form_presenter.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  config/locales/forms/edit_forms/en.yml
Labels: bug

#687 Fix methods checking whether a reg is overseas
  app/forms/concerns/waste_carriers_engine/can_validate_manual_address.rb
  app/forms/waste_carriers_engine/company_address_manual_form.rb
  app/forms/waste_carriers_engine/contact_address_manual_form.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/views/waste_carriers_engine/company_address_manual_forms/new.html.erb
  app/views/waste_carriers_engine/contact_address_manual_forms/new.html.erb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: bug

#686 Complete an edit
  app/controllers/waste_carriers_engine/edit_complete_forms_controller.rb
  app/services/waste_carriers_engine/edit_completion_service.rb
  app/views/waste_carriers_engine/edit_complete_forms/new.html.erb
  config/locales/forms/edit_complete_forms/en.yml
  spec/factories/registration.rb
  spec/requests/waste_carriers_engine/copy_cards_order_completed_forms_spec.rb
  spec/requests/waste_carriers_engine/edit_complete_forms_spec.rb
  spec/services/waste_carriers_engine/edit_completion_service_spec.rb
Labels: enhancement

#690 Update VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/worldpay_initial_request.yml
  spec/cassettes/worldpay_initial_request_invalid.yml
  spec/cassettes/worldpay_redirect.yml
  spec/requests/waste_carriers_engine/worldpay_forms_spec.rb
Labels: housekeeping

#691 Deal with potential location changes in overseas? check
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  spec/forms/waste_carriers_engine/company_address_manual_forms_spec.rb
  spec/forms/waste_carriers_engine/contact_address_manual_forms_spec.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: bug

#692 Copy contact name to contact address when completing edit
  app/services/waste_carriers_engine/edit_completion_service.rb
  spec/services/waste_carriers_engine/edit_completion_service_spec.rb
Labels: bug

#693 Add new transient registration type for NewRegistration
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/models/waste_carriers_engine/new_registration.rb
  spec/factories/new_registration.rb
  spec/models/waste_carriers_engine/new_registration_spec.rb
Labels: enhancement

#697 Add support for feature toggles in the service
  .travis.yml
  app/models/waste_carriers_engine/feature_toggle.rb
  spec/dummy/config/feature_toggles.yml
  spec/models/waste_carriers_engine/feature_toggle_spec.rb
Labels: enhancement

#698 Store a past_registration when completing an edit
  app/models/waste_carriers_engine/past_registration.rb
  app/services/waste_carriers_engine/edit_completion_service.rb
  spec/models/waste_carriers_engine/past_registration_spec.rb
  spec/services/waste_carriers_engine/edit_completion_service_spec.rb
Labels: enhancement

#699 Don't check convictions when doing an edit
  app/controllers/waste_carriers_engine/declaration_forms_controller.rb
Labels: bug

#694 Rename shared post form example to specify renewal specific
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_bank_transfer_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/copy_cards_payment_form_spec.rb
  spec/models/waste_carriers_engine/order_copy_cards_registration_workflow_state/wordpay_form_spec.rb
  spec/requests/waste_carriers_engine/business_type_forms_spec.rb
  spec/requests/waste_carriers_engine/cards_forms_spec.rb
  spec/requests/waste_carriers_engine/cbd_type_forms_spec.rb
  spec/requests/waste_carriers_engine/company_name_forms_spec.rb
  spec/requests/waste_carriers_engine/construction_demolition_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_email_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_name_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_phone_forms_spec.rb
  spec/requests/waste_carriers_engine/declaration_forms_spec.rb
  spec/requests/waste_carriers_engine/declare_convictions_forms_spec.rb
  spec/requests/waste_carriers_engine/location_forms_spec.rb
  spec/requests/waste_carriers_engine/other_businesses_forms_spec.rb
  spec/requests/waste_carriers_engine/payment_summary_forms_spec.rb
  spec/requests/waste_carriers_engine/service_provided_forms_spec.rb
  spec/requests/waste_carriers_engine/tier_check_forms_spec.rb
  spec/requests/waste_carriers_engine/waste_types_forms_spec.rb
  spec/support/shared_examples/post_renewal_form.rb
Labels: enhancement, housekeeping
