Repository DEFRA/waste-carriers-engine, pull requests merged in 2020-05, with the labels that each got.

#823 Update text of pending payment email for new registrations
  config/locales/mailers/new_registration_mailer.en.yml
Labels: enhancement

#822 Split up 'renewal received' page
  app/controllers/waste_carriers_engine/renewal_received_pending_conviction_forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_received_pending_payment_forms_controller.rb
  app/forms/waste_carriers_engine/renewal_received_form.rb
  app/forms/waste_carriers_engine/renewal_received_pending_conviction_form.rb
  app/forms/waste_carriers_engine/renewal_received_pending_payment_form.rb
  app/models/concerns/waste_carriers_engine/can_use_renewing_registration_workflow.rb
  app/views/waste_carriers_engine/renewal_received_pending_conviction_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_received_pending_payment_forms/new.html.erb
  config/locales/forms/renewal_received_pending_conviction_forms/en.yml
  config/locales/forms/renewal_received_pending_payment_forms/en.yml
  config/routes.rb
  spec/factories/forms/renewal_received_form.rb
  spec/forms/waste_carriers_engine/renewal_received_forms_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/confirm_bank_transfer_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_received_pending_conviction_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_received_pending_payment_form_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/worldpay_form_spec.rb
  spec/requests/waste_carriers_engine/renewal_received_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_received_pending_conviction_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_received_pending_payment_forms_spec.rb
  spec/requests/waste_carriers_engine/worldpay_forms_spec.rb
Labels: housekeeping

#824 Add bank transfer details to renewal pending payment page
  app/views/waste_carriers_engine/renewal_received_pending_payment_forms/new.html.erb
  config/locales/forms/renewal_received_pending_payment_forms/en.yml
  spec/requests/waste_carriers_engine/renewal_received_pending_payment_forms_spec.rb
Labels: enhancement

#825 Remove excessive sentence from reg payment pending page
  app/views/waste_carriers_engine/registration_received_pending_payment_forms/new.html.erb
  config/locales/forms/registration_received_pending_payment_forms/en.yml
Labels: bug, enhancement

#826 Make post-QA fixes to bank transfer confirmation pages
  app/views/waste_carriers_engine/shared/_bank_transfer_details.html.erb
  config/locales/forms/registration_received_pending_payment_forms/en.yml
Labels: bug

#828 Add renew via magic link route and function
  app/controllers/waste_carriers_engine/renews_controller.rb
  app/models/waste_carriers_engine/registration.rb
  config/routes.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/requests/waste_carriers_engine/renews_spec.rb
Labels: enhancement

#829 Add new confirmation screen for pending WorldPay payment
  app/controllers/waste_carriers_engine/registration_received_pending_worldpay_payment_forms_controller.rb
  app/forms/waste_carriers_engine/registration_received_pending_worldpay_payment_form.rb
  app/mailers/waste_carriers_engine/new_registration_mailer.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/models/waste_carriers_engine/transient_registration.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_worldpay_payment.html.erb
  app/views/waste_carriers_engine/registration_received_pending_worldpay_payment_forms/new.html.erb
  config/locales/forms/registration_received_pending_worldpay_payment_forms/en.yml
  config/locales/mailers/new_registration_mailer.en.yml
  config/routes.rb
  spec/factories/finance_details.rb
  spec/factories/new_registration.rb
  spec/factories/order.rb
  spec/models/waste_carriers_engine/new_registration_workflow/worldpay_form_spec.rb
  spec/requests/waste_carriers_engine/registration_received_pending_worldpay_payment_forms_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
Labels: enhancement

#830 Fix reliance on defunct renewal_submitted_form state
  app/models/waste_carriers_engine/renewing_registration.rb
  app/models/waste_carriers_engine/transient_registration.rb
  spec/factories/renewing_registration.rb
  spec/mailers/waste_carriers_engine/renewal_mailer_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
  spec/support/shared_examples/transient_registration_named_scopes.rb
Labels: bug

#832 Implement renew via magic link journey happy path
  app/controllers/concerns/waste_carriers_engine/can_redirect_form_to_correct_path.rb
  app/controllers/waste_carriers_engine/forms_controller.rb
  app/controllers/waste_carriers_engine/renew_registration_forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_start_forms_controller.rb
  app/controllers/waste_carriers_engine/renews_controller.rb
  app/models/waste_carriers_engine/edit_registration.rb
  app/models/waste_carriers_engine/registration.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  app/services/waste_carriers_engine/renewing_registration_permission_checks_service.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/requests/waste_carriers_engine/renew_registration_forms_spec.rb
  spec/requests/waste_carriers_engine/renews_spec.rb
  spec/services/waste_carriers_engine/renewing_registration_permission_checks_service_spec.rb
Labels: enhancement

#833 Hide registration type info on Lower Tier info panel
  app/views/shared/_company_details_panel.html.erb
  app/views/waste_carriers_engine/cease_or_revoke_forms/new.html.erb
  app/views/waste_carriers_engine/ceased_or_revoked_confirm_forms/new.html.erb
Labels: bug

#835 Add transition state for cancelling registrations
  app/models/concerns/waste_carriers_engine/can_change_registration_status.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: enhancement

#836 Externalise go back and create overrides to concerns
  app/controllers/concerns/waste_carriers_engine/cannot_go_back_form.rb
  app/controllers/concerns/waste_carriers_engine/unsubmittable_form.rb
  app/controllers/waste_carriers_engine/cannot_renew_company_no_change_forms_controller.rb
  app/controllers/waste_carriers_engine/cannot_renew_lower_tier_forms_controller.rb
  app/controllers/waste_carriers_engine/cannot_renew_type_change_forms_controller.rb
  app/controllers/waste_carriers_engine/copy_cards_order_completed_forms_controller.rb
  app/controllers/waste_carriers_engine/edit_cancelled_forms_controller.rb
  app/controllers/waste_carriers_engine/edit_complete_forms_controller.rb
  app/controllers/waste_carriers_engine/registration_completed_forms_controller.rb
  app/controllers/waste_carriers_engine/registration_received_pending_conviction_forms_controller.rb
  app/controllers/waste_carriers_engine/registration_received_pending_payment_forms_controller.rb
  app/controllers/waste_carriers_engine/registration_received_pending_worldpay_payment_forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_complete_forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_received_forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_received_pending_conviction_forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_received_pending_payment_forms_controller.rb
  app/controllers/waste_carriers_engine/renewal_received_pending_worldpay_payment_forms_controller.rb
  app/controllers/waste_carriers_engine/worldpay_forms_controller.rb
Labels: housekeeping

#837 Make sure to include Lower Tier to EPR export
  app/models/waste_carriers_engine/registration.rb
  spec/factories/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: bug

#838 Fix bug on past registration creation at renewal
  app/models/waste_carriers_engine/past_registration.rb
  spec/models/waste_carriers_engine/past_registration_spec.rb
Labels: bug

#839 Add registration already renewed screen for magic link error
  app/controllers/waste_carriers_engine/renews_controller.rb
  app/models/waste_carriers_engine/registration.rb
  app/services/waste_carriers_engine/expiry_check_service.rb
  app/views/waste_carriers_engine/renews/already_renewed.html.erb
  config/locales/forms/renews/en.yml
  spec/factories/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/requests/waste_carriers_engine/renews_spec.rb
Labels: enhancement

#842 Fix issues on renewals via magic link
  app/models/waste_carriers_engine/finance_details.rb
  app/models/waste_carriers_engine/order.rb
  app/models/waste_carriers_engine/past_registration.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  spec/models/waste_carriers_engine/order_spec.rb
  spec/services/waste_carriers_engine/renewal_completion_service_spec.rb
Labels: bug

#840 Add screen for late renewals
  app/controllers/waste_carriers_engine/renews_controller.rb
  app/models/waste_carriers_engine/registration.rb
  app/views/waste_carriers_engine/renews/past_renewal_window.html.erb
  config/locales/forms/renews/en.yml
  spec/factories/registration.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/requests/waste_carriers_engine/renews_spec.rb
Labels: enhancement

#845 Update bundler options on travis
  .travis.yml
Labels: bug

#841 Add page for invalid magic link token
  app/controllers/waste_carriers_engine/renews_controller.rb
  app/views/waste_carriers_engine/renews/invalid_magic_link.html.erb
  config/locales/forms/renews/en.yml
  spec/requests/waste_carriers_engine/renews_spec.rb
Labels: enhancement

#846 Update text on contact email address
  app/views/waste_carriers_engine/contact_email_forms/new.html.erb
  config/locales/forms/contact_email_forms/en.yml
Labels: enhancement

#847 Update content of email sent with pending bank transfer
  app/views/waste_carriers_engine/renewal_mailer/send_renewal_received_pending_payment_email.html.erb
  config/locales/mailers/renewal_mailer.en.yml
  spec/mailers/waste_carriers_engine/renewal_mailer_spec.rb
Labels: enhancement

#848 Update text to reflect latest wireframe changes
  config/locales/forms/renews/en.yml
Labels: enhancement

#849 Add DataLayerHelper for tracking different journeys
  app/helpers/waste_carriers_engine/data_layer_helper.rb
  spec/helpers/waste_carriers_engine/data_layer_helper_spec.rb
Labels: enhancement

#850 Add tiers to data layer
  app/helpers/waste_carriers_engine/data_layer_helper.rb
  spec/helpers/waste_carriers_engine/data_layer_helper_spec.rb
Labels: enhancement

#851 Update registration.rb
  app/models/waste_carriers_engine/registration.rb
Labels: bug

#852 Fix titles rendering on error renew pages
  app/views/waste_carriers_engine/renews/already_renewed.html.erb
  app/views/waste_carriers_engine/renews/invalid_magic_link.html.erb
  app/views/waste_carriers_engine/renews/past_renewal_window.html.erb
  config/locales/forms/renews/en.yml
Labels: enhancement

#853 Update en.yml
  config/locales/forms/check_your_answers_forms/en.yml
Labels: bug

#854 Update en.yml
  config/locales/forms/copy_cards_payment_forms/en.yml
Labels: bug

#855 Update validation messages as per wireframe
  app/forms/concerns/waste_carriers_engine/can_set_custom_error_message.rb
  app/forms/waste_carriers_engine/base_form.rb
  app/forms/waste_carriers_engine/business_type_form.rb
  app/forms/waste_carriers_engine/check_your_answers_form.rb
  app/forms/waste_carriers_engine/location_form.rb
  app/forms/waste_carriers_engine/registration_number_form.rb
  config/locales/forms/business_type_forms/en.yml
  config/locales/forms/cbd_type_forms/en.yml
  config/locales/forms/construction_demolition_forms/en.yml
  config/locales/forms/declare_convictions_forms/en.yml
  config/locales/forms/location_forms/en.yml
  config/locales/forms/other_businesses_forms/en.yml
  config/locales/forms/registration_number_forms/en.yml
  config/locales/forms/service_provided_forms/en.yml
  config/locales/forms/waste_types_forms/en.yml
Labels: enhancement

#856 Add 'finished' button to new reg end pages
  app/views/shared/_registration_finished_button.html.erb
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_conviction_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_payment_forms/new.html.erb
  app/views/waste_carriers_engine/registration_received_pending_worldpay_payment_forms/new.html.erb
  config/locales/shared/registration_finished_button.en.yml
  lib/waste_carriers_engine.rb
  spec/requests/waste_carriers_engine/registration_completed_forms_spec.rb
Labels: enhancement

#857 Add scope to exclude inactive TransientRegistrations
  app/models/waste_carriers_engine/transient_registration.rb
  spec/factories/meta_data.rb
  spec/factories/transient_registration.rb
  spec/models/waste_carriers_engine/transient_registration_spec.rb
Labels: enhancement
