Repository DEFRA/waste-carriers-engine, pull requests merged in 2021-04, with the labels that each got.

#973 Fix test helper about COVID grace window
  spec/support/helpers/grace_windows.rb
Labels: bug

#974 Send lower tier confirmation emails with Notify
  .github/workflows/ci.yml
  Gemfile
  Gemfile.lock
  app/helpers/waste_carriers_engine/application_helper.rb
  app/mailers/waste_carriers_engine/new_registration_mailer.rb
  app/presenters/waste_carriers_engine/certificate_presenter.rb
  app/services/waste_carriers_engine/notify/base_send_email_service.rb
  app/services/waste_carriers_engine/notify/registration_activated_email_service.rb
  app/services/waste_carriers_engine/registration_activation_service.rb
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.html.erb
  app/views/waste_carriers_engine/new_registration_mailer/registration_activated.txt.erb
  app/views/waste_carriers_engine/pdfs/certificate.html.erb
  spec/cassettes/notify_registration_activated_sends_an_email.yml
  spec/mailers/waste_carriers_engine/new_registration_mailer_spec.rb
  spec/models/waste_carriers_engine/address_spec.rb
  spec/services/waste_carriers_engine/notify/registration_activated_email_service_spec.rb
  spec/services/waste_carriers_engine/registration_activation_service_spec.rb
  spec/support/vcr.rb
Labels: enhancement

#976 Configure defra_ruby_email gem
  config/initializers/defra_ruby_email.rb
Labels: bug

#975 Send upper tier confirmation emails with Notify
  app/services/waste_carriers_engine/notify/registration_activated_email_service.rb
  config/locales/mailers/new_registration_mailer.en.yml
  config/locales/notify/en.yml
  spec/cassettes/notify_lower_tier_registration_activated_sends_an_email.yml
  spec/cassettes/notify_upper_tier_registration_activated_sends_an_email.yml
  spec/services/waste_carriers_engine/notify/registration_activated_email_service_spec.rb
Labels: enhancement

#980 Send 'registration received pending payment' emails from Notify
  app/mailers/waste_carriers_engine/new_registration_mailer.rb
  app/services/waste_carriers_engine/notify/base_send_email_service.rb
  app/services/waste_carriers_engine/notify/registration_pending_payment_email_service.rb
  app/services/waste_carriers_engine/notify/registration_pending_worldpay_payment_email_service.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_payment.html.erb
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_payment.txt.erb
  app/views/waste_carriers_engine/new_registration_mailer/registration_pending_worldpay_payment.html.erb
  config/locales/mailers/new_registration_mailer.en.yml
  config/locales/notify/en.yml
  spec/cassettes/notify_registration_pending_payment_sends_an_email.yml
  spec/cassettes/notify_registration_pending_worldpay_payment_sends_an_email.yml
  spec/services/waste_carriers_engine/notify/registration_pending_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_pending_worldpay_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
Labels: enhancement

#981 Bump cancancan to v3.2.1
  Gemfile
  Gemfile.lock
Labels: dependencies

#986 Bump gem: rexml in response to: CVE-2021-28965
  Gemfile.lock
Labels: housekeeping
