Repository DEFRA/waste-carriers-engine, pull requests merged in 2022-08, with the labels that each got.

#1242 Feature/ad nil email
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/services/waste_carriers_engine/notify/base_send_email_service.rb
  app/services/waste_carriers_engine/order_copy_cards_completion_service.rb
  app/services/waste_carriers_engine/registration_confirmation_service.rb
  app/views/waste_carriers_engine/copy_cards_order_completed_forms/new.html.erb
  lib/waste_carriers_engine.rb
  spec/dummy/config/initializers/waste_carriers_engine.rb
  spec/services/waste_carriers_engine/notify/copy_cards_awaiting_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/copy_cards_order_completed_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_confirmation_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_pending_conviction_check_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_pending_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_pending_worldpay_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_confirmation_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_pending_checks_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_pending_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_pending_worldpay_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/order_copy_cards_completion_service_spec.rb
  spec/services/waste_carriers_engine/registration_confirmation_service_spec.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
Labels: enhancement

#1245 Adding in CH API down error handling
  app/controllers/waste_carriers_engine/check_registered_company_name_forms_controller.rb
  app/views/waste_carriers_engine/check_registered_company_name_forms/companies_house_down.html.erb
  config/locales/forms/check_registered_company_name_forms/en.yml
  lib/defra_ruby_companies_house.rb
  spec/forms/waste_carriers_engine/check_registered_company_name_forms_spec.rb
  spec/lib/defra_ruby_companies_house_spec.rb
  spec/requests/waste_carriers_engine/check_registered_company_name_forms_spec.rb
  spec/services/waste_carriers_engine/refresh_companies_house_name_service_spec.rb
Labels: enhancement

#1246 Fix/blank contact email
  app/forms/concerns/waste_carriers_engine/can_set_custom_error_message.rb
  app/forms/waste_carriers_engine/contact_email_form.rb
  app/validators/waste_carriers_engine/contact_email_validator.rb
  spec/forms/waste_carriers_engine/contact_email_forms_spec.rb
Labels: bug

#1248 Companies House API down page
  app/views/waste_carriers_engine/check_registered_company_name_forms/companies_house_down.html.erb
Labels: enhancement

#1249 Production debug logging
  app/services/concerns/waste_carriers_engine/can_add_debug_logging.rb
  app/services/waste_carriers_engine/base_registration_permission_checks_service.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
  spec/services/waste_carriers_engine/renewing_registration_permission_checks_service_spec.rb
Labels: housekeeping
