Repository DEFRA/waste-carriers-engine, pull requests merged in 2022-09, with the labels that each got.

#1258 Feature/letter for renewal confirmation
  app/services/waste_carriers_engine/notify/renewal_confirmation_letter_service.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  spec/cassettes/notify_upper_tier_ad_renewal_confirmation_letter.yml
  spec/cassettes/notify_upper_tier_ad_renewal_confirmation_letter_business_name.yml
  spec/cassettes/notify_upper_tier_ad_renewal_confirmation_letter_registered_and_business_name.yml
  spec/cassettes/notify_upper_tier_ad_renewal_confirmation_letter_registered_name.yml
  spec/services/waste_carriers_engine/notify/renewal_confirmation_letter_service_spec.rb
  spec/services/waste_carriers_engine/renewal_completion_service_spec.rb
Labels: enhancement

#1260 Text change for registration complete sending a letter
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  config/locales/forms/registration_completed_forms/en.yml
Labels: enhancement

#1262 Adding in telephone to the search terms
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  spec/support/shared_examples/search_scope.rb
  spec/support/shared_examples/searching_phone_number.rb
Labels: enhancement

#1263 Fixing the partial telephone match
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  spec/support/shared_examples/searching_phone_number.rb
Labels: enhancement

#1265 Fix international phone number format searches
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  spec/support/shared_examples/search_scope.rb
  spec/support/shared_examples/searching_phone_number.rb
Labels: bug

#1266 Chore/govpay rebase
  Gemfile.lock
  app/controllers/waste_carriers_engine/check_registered_company_name_forms_controller.rb
  app/forms/concerns/waste_carriers_engine/can_set_custom_error_message.rb
  app/forms/waste_carriers_engine/contact_email_form.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/services/concerns/waste_carriers_engine/can_add_debug_logging.rb
  app/services/waste_carriers_engine/base_registration_permission_checks_service.rb
  app/services/waste_carriers_engine/notify/base_send_email_service.rb
  app/services/waste_carriers_engine/notify/renewal_confirmation_letter_service.rb
  app/services/waste_carriers_engine/order_copy_cards_completion_service.rb
  app/services/waste_carriers_engine/registration_completion_service.rb
  app/services/waste_carriers_engine/registration_confirmation_service.rb
  app/services/waste_carriers_engine/renewal_completion_service.rb
  app/validators/waste_carriers_engine/contact_email_validator.rb
  app/views/waste_carriers_engine/check_registered_company_name_forms/companies_house_down.html.erb
  app/views/waste_carriers_engine/copy_cards_order_completed_forms/new.html.erb
  app/views/waste_carriers_engine/registration_completed_forms/new.html.erb
  app/views/waste_carriers_engine/renewal_complete_forms/new.html.erb
  config/locales/forms/check_registered_company_name_forms/en.yml
  config/locales/forms/registration_completed_forms/en.yml
  config/locales/forms/renewal_complete_forms/en.yml
  lib/defra_ruby_companies_house.rb
  lib/waste_carriers_engine.rb
  spec/cassettes/notify_upper_tier_ad_renewal_confirmation_letter.yml
  spec/cassettes/notify_upper_tier_ad_renewal_confirmation_letter_business_name.yml
  spec/cassettes/notify_upper_tier_ad_renewal_confirmation_letter_registered_and_business_name.yml
  spec/cassettes/notify_upper_tier_ad_renewal_confirmation_letter_registered_name.yml
  spec/dummy/config/initializers/waste_carriers_engine.rb
  spec/forms/waste_carriers_engine/check_registered_company_name_forms_spec.rb
  spec/forms/waste_carriers_engine/contact_email_forms_spec.rb
  spec/lib/defra_ruby_companies_house_spec.rb
  spec/requests/waste_carriers_engine/check_registered_company_name_forms_spec.rb
  spec/services/waste_carriers_engine/notify/copy_cards_awaiting_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/copy_cards_order_completed_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_confirmation_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_pending_conviction_check_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_pending_online_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_pending_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_confirmation_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_confirmation_letter_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_pending_checks_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_pending_online_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_pending_payment_email_service_spec.rb
  spec/services/waste_carriers_engine/order_copy_cards_completion_service_spec.rb
  spec/services/waste_carriers_engine/refresh_companies_house_name_service_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
  spec/services/waste_carriers_engine/registration_confirmation_service_spec.rb
  spec/services/waste_carriers_engine/renewal_completion_service_spec.rb
  spec/services/waste_carriers_engine/renewing_registration_permission_checks_service_spec.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
  spec/support/shared_examples/search_scope.rb
  spec/support/shared_examples/searching_phone_number.rb
Labels: housekeeping

#1267 Drop govpay payment success form the error log
  app/controllers/waste_carriers_engine/govpay_forms_controller.rb
  spec/requests/waste_carriers_engine/govpay_forms_spec.rb
Labels: bug

#1268 Fix/govpay config errors
  app/services/waste_carriers_engine/govpay_payment_service.rb
Labels: bug

#1271 Do not log valid but unsuccessful payments unless there is an error
  app/controllers/waste_carriers_engine/govpay_forms_controller.rb
  spec/requests/waste_carriers_engine/govpay_forms_spec.rb
Labels: bug
