Repository DEFRA/waste-carriers-engine, pull requests merged in 2023-10, with the labels that each got.

#1451 Update CHANGELOG
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: housekeeping

#1449 DO NOT MERGE YET !!! [RUBY-2667] front-end user logins permanently disabled
  app/controllers/waste_carriers_engine/renewal_start_forms_controller.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  spec/models/waste_carriers_engine/new_registration_workflow/start_form_spec.rb
  spec/requests/waste_carriers_engine/renewal_start_forms_spec.rb
  spec/requests/waste_carriers_engine/start_forms_spec.rb
Labels: housekeeping

#1453 Refactor to remove duplicate upper_tier definition
  .rubocop.yml
  app/controllers/waste_carriers_engine/govpay_forms_controller.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/waste_carriers_engine/registration.rb
  spec/dummy/config/application.rb
  spec/services/waste_carriers_engine/notify/registration_confirmation_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/registration_confirmation_letter_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_confirmation_email_service_spec.rb
  spec/services/waste_carriers_engine/notify/renewal_confirmation_letter_service_spec.rb
Labels: housekeeping

#1455 Ruby 2378 wcr renewals overseas company can not renew due to non uk company number
  app/models/concerns/waste_carriers_engine/can_use_renewing_registration_workflow.rb
  lib/defra_ruby_companies_house.rb
  spec/forms/waste_carriers_engine/check_registered_company_name_forms_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_workflow/renewal_information_form_spec.rb
  spec/requests/waste_carriers_engine/check_registered_company_name_forms_spec.rb
Labels: bug

#1456 Add new cannot-register pages for non-england locations
  app/controllers/waste_carriers_engine/must_register_in_northern_ireland_forms_controller.rb
  app/controllers/waste_carriers_engine/must_register_in_scotland_forms_controller.rb
  app/controllers/waste_carriers_engine/must_register_in_wales_forms_controller.rb
  app/forms/waste_carriers_engine/must_register_in_northern_ireland_form.rb
  app/forms/waste_carriers_engine/must_register_in_scotland_form.rb
  app/forms/waste_carriers_engine/must_register_in_wales_form.rb
  app/models/concerns/waste_carriers_engine/can_use_new_registration_workflow.rb
  app/views/waste_carriers_engine/must_register_in_northern_ireland_forms/new.html.erb
  app/views/waste_carriers_engine/must_register_in_scotland_forms/new.html.erb
  app/views/waste_carriers_engine/must_register_in_wales_forms/new.html.erb
  config/locales/forms/must_register_in_northern_ireland_forms/en.yml
  config/locales/forms/must_register_in_scotland_forms/en.yml
  config/locales/forms/must_register_in_wales_forms/en.yml
  config/routes.rb
  spec/factories/forms/must_register_in_northern_ireland_form.rb
  spec/factories/forms/must_register_in_scotland_form.rb
  spec/factories/forms/must_register_in_wales_form.rb
  spec/forms/waste_carriers_engine/must_register_in_northern_ireland_forms_spec.rb
  spec/forms/waste_carriers_engine/must_register_in_scotland_forms_spec.rb
  spec/forms/waste_carriers_engine/must_register_in_wales_forms_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/location_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/register_in_northern_ireland_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/register_in_scotland_form_spec.rb
  spec/models/waste_carriers_engine/new_registration_workflow/register_in_wales_form_spec.rb
  spec/requests/waste_carriers_engine/must_register_in_northern_ireland_forms_spec.rb
  spec/requests/waste_carriers_engine/must_register_in_scotland_forms_spec.rb
  spec/requests/waste_carriers_engine/must_register_in_wales_forms_spec.rb
Labels: enhancement
