Repository DEFRA/waste-carriers-engine, pull requests merged in 2023-11, with the labels that each got.

#1461 Align with govpay gem error handling
  Gemfile.lock
  spec/services/waste_carriers_engine/govpay_payment_details_service_spec.rb
Labels: housekeeping

#1466 Fix/ruby 2793 defra ruby govpay config
  Gemfile
  Gemfile.lock
  app/controllers/waste_carriers_engine/govpay_forms_controller.rb
  app/services/waste_carriers_engine/govpay_payment_details_service.rb
  app/services/waste_carriers_engine/govpay_payment_service.rb
  config/initializers/defra_ruby_govpay.rb
  spec/dummy/config/application.rb
  spec/requests/waste_carriers_engine/govpay_forms_spec.rb
  spec/services/waste_carriers_engine/govpay_payment_details_service_spec.rb
  spec/services/waste_carriers_engine/govpay_payment_service_spec.rb
Labels: bug

#1467 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#1469 Feature/ruby 2788 wcr content convictions page addition
  Gemfile.lock
  app/views/pages/conviction_types.html.erb
  config/locales/pages/conviction_types/en.yml
Labels: enhancement

#1470 [RUBY-2780] content change
  config/locales/forms/registration_completed_forms/en.yml
Labels: enhancement

#1473 Drop use of registration account_email attribute
  Gemfile
  Gemfile.lock
  app/controllers/waste_carriers_engine/govpay_forms_controller.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/waste_carriers_engine/edit_registration.rb
  app/presenters/waste_carriers_engine/edit_form_presenter.rb
  app/services/concerns/waste_carriers_engine/can_add_debug_logging.rb
  app/services/waste_carriers_engine/edit_completion_service.rb
  app/services/waste_carriers_engine/govpay_callback_service.rb
  app/views/waste_carriers_engine/edit_forms/new.html.erb
  config/locales/forms/edit_forms/en.yml
  spec/dummy/app/models/ability.rb
  spec/factories/registration.rb
  spec/requests/waste_carriers_engine/check_registered_company_name_forms_spec.rb
  spec/requests/waste_carriers_engine/company_address_forms_spec.rb
  spec/requests/waste_carriers_engine/company_address_manual_forms_spec.rb
  spec/requests/waste_carriers_engine/company_postcode_forms_spec.rb
  spec/requests/waste_carriers_engine/confirm_bank_transfer_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_address_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_address_manual_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_postcode_forms_spec.rb
  spec/requests/waste_carriers_engine/conviction_details_forms_spec.rb
  spec/requests/waste_carriers_engine/declaration_forms_spec.rb
  spec/requests/waste_carriers_engine/edit_complete_forms_spec.rb
  spec/requests/waste_carriers_engine/govpay_forms_spec.rb
  spec/requests/waste_carriers_engine/invalid_company_status_forms_spec.rb
  spec/requests/waste_carriers_engine/main_people_forms_spec.rb
  spec/requests/waste_carriers_engine/payment_method_confirmation_forms_spec.rb
  spec/requests/waste_carriers_engine/registration_number_forms_spec.rb
  spec/requests/waste_carriers_engine/renew_registration_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_complete_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_received_pending_govpay_payment_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_received_pending_payment_forms_spec.rb
  spec/requests/waste_carriers_engine/renewal_start_forms_spec.rb
  spec/services/waste_carriers_engine/renewal_completion_service_spec.rb
  spec/services/waste_carriers_engine/renewing_registration_permission_checks_service_spec.rb
  spec/support/shared_examples/post_renewal_form.rb
  spec/support/shared_examples/post_without_params_form.rb
  spec/support/shared_examples/request_get_flexible_form.rb
  spec/support/shared_examples/request_get_locked_in_form.rb
Labels: housekeeping

#1474 Updating defra_ruby_area and other dependencies
  Gemfile.lock
  app/controllers/waste_carriers_engine/forms_controller.rb
  app/controllers/waste_carriers_engine/renews_controller.rb
  app/forms/waste_carriers_engine/person_form.rb
  app/helpers/waste_carriers_engine/application_helper.rb
  app/models/waste_carriers_engine/past_registration.rb
  waste_carriers_engine.gemspec
Labels: dependencies

#1475 fix/RUBY-2762_legacy_account_email_values
  app/models/waste_carriers_engine/past_registration.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  spec/models/waste_carriers_engine/past_registration_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
Labels: bug

#1476 update defra_ruby_area dependency
  Gemfile.lock
  waste_carriers_engine.gemspec
Labels: dependencies
