Repository DEFRA/waste-carriers-engine, pull requests merged in 2024-01, with the labels that each got.

#1484 [RUBY-2779] updating password hint on password reset page
  app/views/devise/passwords/edit.html.erb
  config/locales/devise.en.yml
Labels: enhancement

#1487 Fix/ruby 2805 postcode validation
  Gemfile.lock
  app/forms/waste_carriers_engine/company_postcode_form.rb
  app/forms/waste_carriers_engine/contact_postcode_form.rb
  app/validators/waste_carriers_engine/address_lookup_validator.rb
  spec/requests/waste_carriers_engine/company_address_manual_forms_spec.rb
  spec/requests/waste_carriers_engine/contact_address_manual_forms_spec.rb
  spec/support/shared_examples/validate_postcode.rb
  waste_carriers_engine.gemspec
Labels: bug

#1492 [RUBY-2842] refactoring original_activation_date method to handle situation when dateActivated is missing
  app/models/waste_carriers_engine/registration.rb
  spec/models/waste_carriers_engine/registration_spec.rb
Labels: bug

#1493 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#1490 Move analytics services to the back office
  Gemfile.lock
  app/models/waste_carriers_engine/analytics/page_view.rb
  app/models/waste_carriers_engine/analytics/user_journey.rb
  app/services/waste_carriers_engine/analytics/aggregated_analytics_service.rb
  app/services/waste_carriers_engine/analytics/registrations_completed_analytics_service.rb
  app/services/waste_carriers_engine/analytics/user_journey_service.rb
  config/routes.rb
  spec/factories/user_journey.rb
  spec/models/waste_carriers_engine/analytics/user_journey_spec.rb
  spec/requests/waste_carriers_engine/renewal_complete_forms_spec.rb
  spec/requests/waste_carriers_engine/start_forms_spec.rb
  spec/services/waste_carriers_engine/analytics/aggregated_analytics_service_spec.rb
  spec/services/waste_carriers_engine/analytics/registrations_completed_analytics_service_spec.rb
  spec/services/waste_carriers_engine/analytics/user_journey_service_spec.rb
Labels: housekeeping

#1495 Add back-office user journey completion pages
  app/models/waste_carriers_engine/analytics/user_journey.rb
  spec/services/waste_carriers_engine/analytics/user_journey_service_spec.rb
Labels: enhancement

#1497 Revert 'Outside England' / 'Not found' change
  app/services/waste_carriers_engine/determine_area_service.rb
  spec/services/waste_carriers_engine/determine_area_service_spec.rb
Labels: bug
