Repository DEFRA/waste-carriers-engine, pull requests merged in 2024-10, with the labels that each got.

#1573 [RUBY-3316] Add context to delete user action
  app/views/waste_carriers_engine/conviction_details_forms/new.html.erb
  app/views/waste_carriers_engine/main_people_forms/new.html.erb
  config/locales/forms/conviction_details_forms/en.yml
  config/locales/forms/main_people_forms/en.yml
Labels: enhancement

#1575 Revert address area change to not update area attribute
  app/models/waste_carriers_engine/address.rb
  spec/models/waste_carriers_engine/address_spec.rb
  spec/services/waste_carriers_engine/update_address_details_from_os_places_service_spec.rb
Labels: bug

#1574 Chore/ruby 3409 mongoid reference one
  app/controllers/waste_carriers_engine/company_address_forms_controller.rb
  app/controllers/waste_carriers_engine/company_address_manual_forms_controller.rb
  app/forms/waste_carriers_engine/address_lookup_form_base.rb
  app/forms/waste_carriers_engine/company_address_form.rb
  app/forms/waste_carriers_engine/company_address_manual_form.rb
  app/forms/waste_carriers_engine/contact_address_manual_form.rb
  app/models/concerns/waste_carriers_engine/can_have_registration_attributes.rb
  app/models/concerns/waste_carriers_engine/can_reference_single_document_in_collection.rb
  app/models/waste_carriers_engine/address.rb
  app/views/waste_carriers_engine/company_address_forms/new.html.erb
  config/locales/forms/company_address_forms/en.yml
  config/locales/forms/contact_address_forms/en.yml
  spec/factories/forms/company_address_form.rb
  spec/forms/waste_carriers_engine/company_address_forms_spec.rb
  spec/forms/waste_carriers_engine/company_address_manual_forms_spec.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/requests/waste_carriers_engine/company_address_forms_spec.rb
  spec/requests/waste_carriers_engine/company_address_manual_forms_spec.rb
  spec/services/waste_carriers_engine/registration_completion_service_spec.rb
  spec/support/shared_examples/can_have_registration_attributes.rb
  spec/support/shared_examples/search_scope.rb
Labels: housekeeping

#1582 Chore/ruby 3409 mongoid reference one
  app/views/waste_carriers_engine/company_address_manual_forms/new.html.erb
Labels: bug

#1583 RUBY-3433: Tech Debt : remove devise and cancancan gems + remove front-office users from wcr engine
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/waste_carriers_engine/application_controller.rb
  app/controllers/waste_carriers_engine/transient_registrations_controller.rb
  app/models/waste_carriers_engine/renewing_registration.rb
  app/services/waste_carriers_engine/base_registration_permission_checks_service.rb
  app/services/waste_carriers_engine/flow_permission_checks_service.rb
  app/services/waste_carriers_engine/govpay_payment_service.rb
  app/services/waste_carriers_engine/renewing_registration_permission_checks_service.rb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  config/locales/activemodel.en.yml
  config/locales/devise.en.yml
  config/routes.rb
  spec/dummy/app/models/user.rb
  spec/dummy/config/initializers/devise.rb
  spec/dummy/config/routes.rb
  spec/factories/renewing_registration.rb
  spec/factories/user.rb
  spec/models/waste_carriers_engine/conviction_sign_off_spec.rb
  spec/models/waste_carriers_engine/finance_details_spec.rb
  spec/models/waste_carriers_engine/new_registration_spec.rb
  spec/models/waste_carriers_engine/order_spec.rb
  spec/models/waste_carriers_engine/payment_spec.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/models/waste_carriers_engine/renewing_registration_spec.rb
  spec/rails_helper.rb
  spec/requests/waste_carriers_engine/confirm_bank_transfer_forms_spec.rb
  spec/requests/waste_carriers_engine/govpay_forms_spec.rb
  spec/requests/waste_carriers_engine/transient_registrations_spec.rb
  spec/services/waste_carriers_engine/analytics/user_journey_service_spec.rb
  spec/services/waste_carriers_engine/blank_permission_check_service_spec.rb
  spec/services/waste_carriers_engine/build_new_registration_finance_details_service_spec.rb
  spec/services/waste_carriers_engine/build_order_copy_cards_finance_details_service_spec.rb
  spec/services/waste_carriers_engine/build_renewal_finance_details_service_spec.rb
  spec/services/waste_carriers_engine/certificate_generator_service_spec.rb
  spec/services/waste_carriers_engine/flow_permission_checks_service_spec.rb
  spec/services/waste_carriers_engine/govpay_callback_service_spec.rb
  spec/services/waste_carriers_engine/govpay_payment_details_service_spec.rb
  spec/services/waste_carriers_engine/govpay_payment_service_spec.rb
  spec/services/waste_carriers_engine/renewing_registration_permission_checks_service_spec.rb
  spec/support/shared_examples/build_finance_details.rb
  spec/support/shared_examples/post_renewal_form.rb
  spec/support/shared_examples/post_without_params_form.rb
  spec/support/shared_examples/transient_registration_named_scopes.rb
Labels: housekeeping
